### ISSUE TITLE
Support for extensionless permalinks - no trailing slash or .html

### ISSUE THREAD

**Issue by jehartzog** [sergiokopplin/indigo#100]
First of all, thanks for the work on this template and build scripts, it is a fantastic start to someone new to both Jeykll and most of the other tools in here!

When building my site, I noticed that using [extensionless permalinks](https://jekyllrb.com/docs/permalinks/#extensionless-permalinks) led to 404 errors on the dev server and caused the Travis to build to fail. For example, a global permalink like `permalink: /:categories/:title` in _config.yml triggers these issues. While GitHub pages and the Jekyll built-in server have support for not having the trailing slash for an html file, that didn't help with development and testing.

I was able to fix the Travis tests by updating html-proofer to [greater than 3.0](https://github.com/gjtorikian/html-proofer/pull/311) in deleting the Gemfile.lock and re-running `bundle install` and then editing the travis.sh file to execute

```
bundle exec htmlproofer ./_site --only-4xx --assume-extension
```

One easy to miss [change](https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0) is that with 3.0 the binary name changed from `htmlproof` to `htmlproofer`

For the dev server running via gulp, I only got a rough workaround by editing _config_dev.yml to add the trailing slash back in, which allowed me to not have trailing slashes in production but the dev examples to still work. I'm trying to think of a better way to fix the dev server but haven't seen a way yet.

I plan on issuing a PR to make use of the extensionless URL feature in Jekyll, but I suspect there is a better way to fix the dev server that doesn't require making it use different URL's than production.

**Comment by sergiokopplin** [comment]
PR merged!
