### ISSUE TITLE
Add sitemap.xml generation

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#105]
Is it possible to add sitemap.xml generation?

**Comment by jehartzog** [comment]
It already is. Look at [_.config.yml](https://github.com/sergiokopplin/indigo/blob/gh-pages/_config.yml) line 74, which activates the [Jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap) plugin.

It silently generates sitemap.xml for you, but you only see it in the compiled site under the _site directory which isn't synced to the repo. It is generated by github pages just fine though.

**Comment by mehmandarov** [comment]
You are absolutely right. Sorry about that! Thanks!

**Comment by sergiokopplin** [comment]
@mehmandarov if you have another doubt, open a issue.

---

Thank you again @jehartzog

**Comment by mehmandarov** [comment]
Thanks! @sergiokopplin
