### ISSUE TITLE
Why do backtick-style code highlighting not work?

### ISSUE THREAD

**Issue by AGresvig** [sergiokopplin/indigo#116]
First off, thanks for a fantastic theme! So clean, and well featured.

I cannot get the new backtick-style code highlighting feature of [github-pages 3.0](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to work.

I also see examples use old-style `{% highlight lang %}` syntax.

What's missing for it to work?

Thanks!

**Comment by sergiokopplin** [comment]
You have to write in the Jekyll way.
Jekyll uses Rouge to compile code for markdown, so you must use the `{% something %}`.

---

References:
- [https://jekyllrb.com/docs/templates/#code-snippet-highlighting](https://jekyllrb.com/docs/templates/#code-snippet-highlighting)
- [http://rouge.jneen.net/](http://rouge.jneen.net/)
