### ISSUE TITLE
Replace Stylus with Sass

### ISSUE THREAD

**Issue by sergiokopplin** [sergiokopplin/indigo#117]
Originally from #81, in the final discussion.

---

Related - replace Stylus with SASS

@sergiokopplin one more thing which is kind of related, all this pain to ensure a setup MUST be done because of the need to use stylus, which also means you can't update any css without working with your full dev environment.

I am in a unique situation where most of the day I can only use the Github website (can't install any dev software), so I wanted to be able to fully edit the site without needing to recompile on my own computer. I realized that Jekyll has SASS support build in, so I converted the entire styling to using SASS on my fork (I have not yet filled in any template to that fork).

GitHub pages can even inline the sass after compiling it, so the template works just as slick as before but is less dependent on external libraries.

I don't know if you would consider making this shift, but I believe that it would be very helpful for users if they could have a version of the template that requires NO development environment setup, they can just edit via github.com, or edit/upload files directly with git and let the server do all the compiling.

I've been making a lot of changes to the template while assembling my own site, but I'm trying to keep track of the improvements I'm making so I can break them out back to the template for others to use.

**Comment by jehartzog** [comment]
@sergiokopplin, let me know if you think this is worth a shift for your project, I needed it for my own reasons (can only use github web portal during work hours), but it's obviously a big shift for the template.

Another benefit is that it cleans up the file structure and makes it ever easier to follow how everything works; the css files are gone, no need to compile and copy over (or run gulp to do it), all the SASS files rest in a single_sass folder which is auto-inlined directly into final html.

I already completed the code changes along with some other shifts at [my fork](https://github.com/jehartzog/indigo), let me know if you want me to put together a PR for shifting from Stylus to the built-in SASS. I will just have to remove some of the extra CSS I added in.

**Comment by sergiokopplin** [comment]
@jehartzog i'm doing here. https://github.com/sergiokopplin/indigo/tree/sass

I'm planning to move to sass right now!
We have a lot of benefits, so why not?

**Comment by sergiokopplin** [comment]
@jehartzog i think now it's reaky to be replaced! Can you take a look on the code? Thank you

**Comment by jehartzog** [comment]
I have a few updates, finishing them up now!

**Comment by jehartzog** [comment]
You work very quickly! It took me longer to shift over to SASS, but also because I wanted to use SCSS format rather than SASS which takes extra conversion but isn't needed. I sent the PR #120 with a few additions and to inline the compiled CSS.

**Comment by sergiokopplin** [comment]
I'm testing all the pages now, we can merge all this tomorrow. Looking for improvements!

**Comment by sergiokopplin** [comment]
Merged! Testing!
