### ISSUE TITLE
'page' layout: margin-top

### ISSUE THREAD

**Issue by dwlfrth** [sergiokopplin/indigo#123]
Hello Sergio,

First of all, thanks for the great theme!
I'd like to know if it's on purpose (I'd say yes since the condition is explicitly for that) that 'layouts/default.html' do not use 'page' as a class when the page title is not "About" or "404".

What is the reason behind that ?

Create new pages do no benefit the 'margin-top' of the CSS without having to modify original code.

Let me know!

**Comment by dwlfrth** [comment]
Am I right assuming the the condition is in place not to have a margin when we display the "header" (the block containing the profile pic, the name, the bio and the social links) ?

If yes, shouldn't the condition be

{% if showHeader != true %}

rather than

{% if page.title == "About" or page.title == "404" %}

That would make the page rendering a bit more "standard" and "dynamic" since the condition will exists at only one place (top of _includes/header.html)

**Comment by sergiokopplin** [comment]
@dwlfrth thank you for your questions!

---

So,
What you think about a pull request, can you make one with these changes?

**Comment by dwlfrth** [comment]
I sure can.
Just wanted to know if I was right about that condition in 'layouts/default.html' ?
(To avoid getting the margin-top when the "header" is displayed)

**Comment by sergiokopplin** [comment]
Thanks @dwlfrth. Nice pull request!
