### ISSUE TITLE
@import for google fonts not working with sass

### ISSUE THREAD

**Issue by sayakbiswas** [sergiokopplin/indigo#124]
Hi,

First of all thank you so much for the amazing theme. I am using it for my personal website. 

I customized it minimally by adding the Raleway, Fira Sans and the PT Serif google fonts. I was able to use @import statements to load these fonts from google fonts back with the stylus files. But now with sass, this doesn't seem to work anymore. So, I ended up putting them as <link>(s) in the _layouts/default.html file.

Is there a way to make them work with sass/scss?

**Comment by sergiokopplin** [comment]
you did like this?
`@import url(http://fonts.googleapis.com/css?family=Roboto+Slab|Open+Sans:400italic,700italic,400,700);`

**Comment by sayakbiswas** [comment]
Yes, let me share my import statements with you once I get to my PC.

**Comment by sayakbiswas** [comment]
Okay, so this is what I used:
`@import url(https://fonts.googleapis.com/css?family=Raleway:400,400italic,500,300,300italic,600,600italic,700,700italic,500italic);`

**Comment by sergiokopplin** [comment]
Is it now working?

**Comment by sayakbiswas** [comment]
No Sergio.

**Comment by sergiokopplin** [comment]
I'll try later. But seems ok. If is not working, something is missing.

**Comment by sayakbiswas** [comment]
Sure, let me know if you need anything else.

**Comment by sergiokopplin** [comment]
I didn't find any answers for this question.
You can put your fonts in the html, that's the way in this case.

**Comment by sayakbiswas** [comment]
Okay, cool. Thanks for looking into it.

**Comment by Cyril147** [comment]
How use <link> put google font inside the web?
