### ISSUE TITLE
how to add new sections to the website apart from Blog Projects and About ? 

### ISSUE THREAD

**Issue by ameya0111** [sergiokopplin/indigo#133]
Hello I was wondering how I can add a new Section to my website. 
It has to be like Projects not like a Blog.

Thanks.

**Comment by ameya0111** [comment]
I was able to add the new sections that I wanted. It involved making changes to the _include, _sass directories, and the _config.yml files.

**Comment by sergiokopplin** [comment]
Do you need something else?
