### ISSUE TITLE
Adding HTML file with CSS and JS in post

### ISSUE THREAD

**Issue by laurenmackey** [sergiokopplin/indigo#136]
I have an interactive map I want to load into a post. I have it as an HTML file that links to CSS and JS files. How do I incorporate all three file types? I can only get it to load the HTML but not the other two within the post.

**Comment by sergiokopplin** [comment]
@laurenmackey, do you have an example inside github?

**Comment by jehartzog** [comment]
I'm not sure if this is what you want, but I was able to include inline CSS and JS into a single post [here](https://raw.githubusercontent.com/jehartzog/jehartzog.github.io/master/_posts/2016-05-23-countdown-to-freedom.markdown). I used it to make a [javascript countdown](http://www.johnehartzog.com/blog/countdown-to-freedom).

**Comment by sergiokopplin** [comment]
@jehartzog - thank you for the answer.

**Comment by sergiokopplin** [comment]
@laurenmackey do you need something else?

**Comment by laurenmackey** [comment]
Sorry haven't had a chance to try this out myself, but it looks like I can get it to work. Thanks for the help!

**Comment by njudd** [comment]
Is it possible to have a project listed that just links to an HTML page? Specifically, I am wondering about knitted HTML pages from Rstudio?

This was the most relevant post I could find yet the links are dead

---- solution ----

You make a markdown file with the following header
```
---
title: "insert title"
layout: post
date: 2021-05-23 22:10
projects: true
hidden: true # don't count this post in blog pagination
description: "Training spatial cognition enhances mathematical learning in a randomized study of 17,000 children"
category: project
externalLink: https://site.com/2021-11-12-html-std-residualization.html
---
```

You then can put which ever HTML project you wish in your main dir.
