### ISSUE TITLE
Add support for several authors

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#137]
Is it possible to add support for several authors to post content to the blog? (New author = Name + Profile picture).

**Comment by sergiokopplin** [comment]
Not today, we have to create this function.
We have to update the SEO, the config files and the layout. It's not so simple, but we can try.

---

What do we need: different authors with names, pictures, social links, etc. Something else?

**Comment by mehmandarov** [comment]
@sergiokopplin: Yes, I think it is a pretty good start. We should be able to tag posts with a username in the front matter and by that defining the authorfor the post. Also a default user, so we dont break the previous posts.

**Comment by sergiokopplin** [comment]
done. take a look #141 

o//

**Comment by mehmandarov** [comment]
Wow you are quick! Awesome fixes! Thanks!! I will have a look at that tomorrow! \o/
