### ISSUE TITLE
Improve Twitter Summary Card

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#138]
Improve Twitter summary card to contain a picture if available in the post, or author picture if no picture is available in the post. Optional: Add possibility to choose a picture for share cards (Twitter, Facebook, etc.). Example: https://dev.twitter.com/cards/types/summary-large-image.

**Comment by sergiokopplin** [comment]
![screen shot 2016-06-18 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/2743180/16172235/8c39c98a-355a-11e6-8071-79b6bca90fbb.png)

done!

**Comment by mehmandarov** [comment]
Wow, you are quick! Awesome fixes! Thanks!!
