### ISSUE TITLE
Introduce search function

### ISSUE THREAD

**Issue by Fohlen** [sergiokopplin/indigo#14]
Are there any plans to enhance the blog site with a search function?
It could be added to the Blog Navbar (on the left side or beneath).
I added a screen shot marking possibly nice positions.
![bildschirmfoto_2016-02-18_22-43-07](https://cloud.githubusercontent.com/assets/3730888/13159308/58bfc30c-d691-11e5-9899-1e3c9022cb2c.png)

**Comment by sergiokopplin** [comment]
@Fohlen look at this: http://willianjusten.com.br/
Is that what you mean?

We can try that, for shure!

**Comment by Fohlen** [comment]
Yes, this would be awesome.
Probably it will be necessary to use categories / keywords to identify posts, I don't know if Jekyll supports full-text search though, hmm.

**Comment by sergiokopplin** [comment]
Yes you can, but i don't believe that we can do with full-text inside the content itself. 
Take a look at this: https://github.com/willianjusten/willianjusten.github.io/blob/master/search.json

This is how we do search in jekyll.

**Comment by sergiokopplin** [comment]
i'm doing this, maybe this week.
what we have to do:
- [ ] export data for json
- [ ] include minimum js for search
- [ ] layouts

**Comment by sergiokopplin** [comment]
http://jekyll.tips/tutorials/search/

**Comment by sergiokopplin** [comment]
@Fohlen i'm not going to do that. After some days i decided to not apply the search function because jekyll doesn't have search native. 
I know this is bad, but i'm not seeing any advantage, so i'm closing the issue.
