### ISSUE TITLE
How to change the tab name?

### ISSUE THREAD

**Issue by lichen999** [sergiokopplin/indigo#140]
I would like to rename projects and Blog into other names. Thanks!

**Comment by mehmandarov** [comment]
+1 :-)

**Comment by sergiokopplin** [comment]
You can't do that. 
I was looking the code and it's too much linked inside with file names and configurations.

---

Can we solve this in other way?

**Comment by manifestlifeinc** [comment]
I was able to change the the "Home" Tag
[Example](http://www.manifest.life/blog/)
- Replaced "Home" with "Manifest Life" **line 1** `_includes/header.html`

```
{% if page.title == "**Manifest Life**"
   or page.title == "Blog"
   or page.title == "Projects"
   or page.title == "Tags"
%}{% assign showHeader = true %}{% endif %}
```
- Replaced "Home" with "Manifest Life" **line 1-7** [_includes/nav.html](url)

```
<nav class="{% if page.title == "Manifest Life" %}nav-Manifest Life{% else %}nav{% endif %}">
    <ul class="list">
        {% if page.title != "Manifest Life" %}
            <li class="item">
                <a class="link" href="{{ site.url }}/">Manifest Life</a>
            </li>
        {% endif %}
```
- Finally, at the root `index.html` file

```
---
layout: page
title: Manifest Life
---
```

Hope this helps. @lichen999 @sergiokopplin @mehmandarov

**Comment by sergiokopplin** [comment]
thank you @manifestlifeinc 

---

he's right. we can do, but needs some time to think first, because we have some logical operations with the layout names
