### ISSUE TITLE
anyway I can link project title under the project page directly to github repo?

### ISSUE THREAD

**Issue by cyfyifanchen** [sergiokopplin/indigo#145]
I want it to be able to go to github repo directly without going details of project. Is it possible?

**Comment by sergiokopplin** [comment]
Can you give me more details? I didn't understand.

**Comment by cyfyifanchen** [comment]
If I am on project index page, where has all project titles, I want make those project titles `<a>` tags. So when I click any project titles on project index page, those links take me to my github repo.

**Comment by sergiokopplin** [comment]
done. #152

**Comment by cyfyifanchen** [comment]
Thanks for the the PR to fix this problem. However, the style is wrong after I put `<a>` tag in title as
`title: "<a href='https://www.google.com'>google</a>"
`This line gets pushed down since part of the `.url` style is `display: block`.

**Comment by sergiokopplin** [comment]
Are you putting a link inside the title of the project?
Can you upload a screenshot?

**Comment by cyfyifanchen** [comment]
![image](https://cloud.githubusercontent.com/assets/2340896/16460109/0fad5b20-3de3-11e6-90a2-c36aabf69767.png)

![image](https://cloud.githubusercontent.com/assets/2340896/16460114/199fa110-3de3-11e6-8fa9-01508df774ff.png)

**Comment by sergiokopplin** [comment]
Don't edit the title. Add the link inside externalLink.

```
externalLink: http://google.com
```

**Comment by cyfyifanchen** [comment]
Nice, thanks man.
