### ISSUE TITLE
initpost script

### ISSUE THREAD

**Issue by aallam** [sergiokopplin/indigo#146]
Hello,

The "Initpost.sh" script is not working for me correctly because it generates a post with wrong time form (hh:mm:ss) which Jekyll does not accept somehow, and the post does not show on the blog.

To solve this, I changed the variable TIME to become : TIME=$(date +"%H:%M"). Now the script works as expected for me.

**Comment by sergiokopplin** [comment]
Can you create a pull request with this?
Thank you

**Comment by sergiokopplin** [comment]
merged! thank you!
