### ISSUE TITLE
Line breaks?

### ISSUE THREAD

**Issue by matkoch** [sergiokopplin/indigo#148]
_I wanna be focused, but first of all - thanks for the theme_ 👍 

I'm wondering why line breaks in mark down files do not create line breaks in generated pages. AFAIK, this would be the normal behavior.... Do I really need to use paragraph tag all the time?

**Comment by matkoch** [comment]
I'm so sorry, had `html` instead of `md`. Will leave this anyways :)

**Comment by sergiokopplin** [comment]
If you need some help, tell me.
