### ISSUE TITLE
Local vs. Server

### ISSUE THREAD

**Issue by matkoch** [sergiokopplin/indigo#149]
Alright, on my local machine, everything works fine. But on github, all the links are broken. You can reach me at skype:ithrowexceptions.

**Comment by matkoch** [comment]
Damnit... It's always 20 minutes wondering, then posting the issue, then solving it myself...

Was missing 'www' for my hostname. Sorry :/

**Comment by sergiokopplin** [comment]
No problems! I do same like this every time. haha
