### ISSUE TITLE
GitHub Icon shown, although username is not specified

### ISSUE THREAD

**Issue by matkoch** [sergiokopplin/indigo#150]
Alright, now I hope that's a real issue. I commented out my github username. However, there is still some icon.

http://matkoch.github.io
https://github.com/matkoch/matkoch.github.io/blob/master/_config.yml

**Comment by matkoch** [comment]
I guess this variable is set somewhere else. For now I excluded all social links, but the issue remains. Having set the github username solves it of course, but is probably not optimal 😔

**Comment by sergiokopplin** [comment]
I'm not seeing the icon here. Are you shure about this?
![screen shot 2016-06-28 at 11 31 29 am](https://cloud.githubusercontent.com/assets/2743180/16419394/e15f0c92-3d23-11e6-9a98-d450ec188679.png)

**Comment by matkoch** [comment]
As I said, I already removed all of the social links.

The issue didn't appear locally, only if commited to github pages.

**Comment by sergiokopplin** [comment]
Hmm, interesting.
The _config file is not from the indigo theme, is that right?
