### ISSUE TITLE
Additional social icons

### ISSUE THREAD

**Issue by matkoch** [sergiokopplin/indigo#151]
Could you provide additional social icons for skype, stackoverflow, and maybe some others?

Alternatively, do you have any source for the existing ones, so I could make a PR ?

_Ps: That's also a real issue_ :grin:

**Comment by sergiokopplin** [comment]
https://github.com/sergiokopplin/indigo/blob/gh-pages/_includes/icons.html

That's the source file for icons.
I was editing the icons in icomoon, i guess.
You have to select the icons (skype, etc) and export as svg and add in that file.

Then you edit the config file and [social-links.html](https://github.com/sergiokopplin/indigo/blob/gh-pages/_includes/social-links.html)

---

can you make the pr?
appreciate it.
