### ISSUE TITLE
Possibility of adding infinite scroll to the blog index page?

### ISSUE THREAD

**Issue by cyfyifanchen** [sergiokopplin/indigo#156]
I know it can be a huge plus to UX, is it possible?

**Comment by sergiokopplin** [comment]
Can you create a PR?

---

references:
- http://tobiasahlin.com/blog/infinite-scroll-with-jekyll/
- https://github.com/tobiasahlin/infinite-jekyll
- https://github.com/ColinEberhardt/jekyll-pagination-infinite-scroll
- http://blog.scottlogic.com/2014/10/14/jekyll-pagination-and-infinite-scrolling.html

**Comment by cyfyifanchen** [comment]
I read the articles you referred. I am not sure if I can make it happen since this site was customized heavily from Jekyll, and I don't have any experience with Jekyll. But I will for sure do more research.

**Comment by dineshnagarit** [comment]
I will also try to implement infinite-scroll at my end. After completing I will  create a PR.

**Comment by sergiokopplin** [comment]
thanks @yifanchen, @dineshnagarit 

---

i'm on a new project, so i don't have time to do right now. 👎
