### ISSUE TITLE
Alignment-Justify for the paragraphs in the post.

### ISSUE THREAD

**Issue by ace139** [sergiokopplin/indigo#159]
When writing the post, its obviously left aligned. But it doesn't look good enough according to me. I think that the paragraphs should be aligned justify.

**Comment by sergiokopplin** [comment]
Are you saying all the paragraphs in all the pages?

**Comment by ace139** [comment]
Yes. I have been seeing many blogs in markdowns, most of them gave the problems. So will it be possible to justify the paragraphs in the post?

Soumyo Dey

On Mon, Jul 18, 2016 at 7:53 PM +0530, "Sérgio A. Kopplin" <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you saying all the paragraphs in all the pages?

##

**Comment by sergiokopplin** [comment]
Take a look!
http://stackoverflow.com/questions/14051715/markdown-native-text-alignment

---

Hope it helps!
