### ISSUE TITLE
Adding Custom Pages

### ISSUE THREAD

**Issue by muggin** [sergiokopplin/indigo#163]
Hi,

First of all, thanks for sharing indigo... I really appreciate how 'clean' and minimalistic it is.
I would like to use indigo as a template to create my own GH Page, but I'd like to add one more page type. Apart from the regular blog, I'd like to have a 'Today I Learned' micro-blog page where I would post just some useful code snippets and information that I pick up on a day to day basis, but I'd like to content of each 'post' to be showed without the need to click on the link.

Wonder if you could give me some tips how to quickly edit this template (I'm completely new to Jekyll).

Thanks in advance 👍

**Comment by muggin** [comment]
@sergiokopplin can I count on your help or should I close this issue? Thanks

**Comment by jehartzog** [comment]
@muggin I can give you a high level overview of how to do this.
- Create a new .html file in [_includes/](https://github.com/sergiokopplin/indigo/tree/gh-pages/_includes) called 'blog-snippets.html'. You'll need to customize this page to show the snippets you want, it should be relatively straightforward using the [Liquid templating language](https://jekyllrb.com/docs/templates/) in Jekyll. You should start with [_includes/blog-post.html](https://github.com/sergiokopplin/indigo/blob/gh-pages/_includes/blog-post.html) and just edit it to add in the first x words of the post.
- Create a new file in the root directory called 'micro-blog.html', copy over the code from [blog/index.html](https://github.com/sergiokopplin/indigo/blob/gh-pages/blog/index.html) and edit it to include your new 'blog-snippets.html'.
- If you visit yoursite.com/micro-blog then you will see your new blog summary post!

**Comment by sergiokopplin** [comment]
@muggin sorry for the delay, i'm on a new job.

---

@jehartzog answer is the right answer. Is it helping you?

**Comment by muggin** [comment]
I tried figuring it out but got stuck and left the idea, unfortunately.

**Comment by ShantanuJoshi** [comment]
Check out this two step blog post that explains how to add new pages this might be able to help you out (step 2) : http://artiannaswamy.com/build-a-github-blog-part-2

**Comment by sergiokopplin** [comment]
Is that solved @muggin?
