### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by jaimejim** [sergiokopplin/indigo#164]
Hi, 

thanks for the work on Indigo, it is really cool. I noticed that the latest build should not pass Travis, is that correct?
![screen shot 2016-08-24 at 13 43 45](https://cloud.githubusercontent.com/assets/1798358/17928003/46051fba-6a01-11e6-9bab-aeb681712693.png)

It is giving me a bit of problems but for another reason:
"Could not find .travis.yml, using standard configuration."

I do not know why is that, as the file is on the repository.

**Comment by sergiokopplin** [comment]
Thanks for the issue.
This is a problem, some people are sending PR when they update their own files on their own forks.

---

Are you having problems yet? I did some updates on files, check out later.
