### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jnanadarshan** [sergiokopplin/indigo#168]
My Installtion failed.
![capture](https://cloud.githubusercontent.com/assets/16976738/18426106/961ebdfa-78dc-11e6-9c1b-7fd2534eac80.PNG)

**Comment by sergiokopplin** [comment]
Have you installed all the gem dependencies?

**Comment by krzysiekpiasecki** [comment]
Run `bundle exec jekyll serve`. It should work.

**Comment by sergiokopplin** [comment]
@jnanadarshan any problems yet?
