### ISSUE TITLE
Unable to setup projects (URL clash perhaps )?

### ISSUE THREAD

**Issue by abhi18av** [sergiokopplin/indigo#170]
Hi @sergiokopplin 

I've been using this awesome template but I've run into a problem)

I have this project [Github Resume](https://github.com/abhi18av/resume)

![screenshot from 2016-09-20 16-03-07](https://cloud.githubusercontent.com/assets/12799326/18668742/d218ff18-7f54-11e6-936c-ed1ac3c014e0.png)

And it says the website is served under the **abhi18av.github.io/resume**  domain but on the domain it only shows a blank page.

![screenshot from 2016-09-20 16-03-22](https://cloud.githubusercontent.com/assets/12799326/18668744/ddcad458-7f54-11e6-9e13-27bbda4aa1e3.png)

Do you have any ideas how to correct it? I'd really appreciate your help ;)

**Comment by sergiokopplin** [comment]
you must work on gh-pages branch, i guess

**Comment by abhi18av** [comment]
As in? What does that mean, I'm sorry I didn't get you that well. In the repo there's no travis build etc so why do I still need to link it to gh-pages?

**Comment by sergiokopplin** [comment]
For example:

I have my master rep, which is https://github.com/sergiokopplin/sergiokopplin.github.io.
That repo goes to https://koppl.in and i work on master.

Every subdomain like http://koppl.in/indigo has to be a repository with "gh-pages" branch, instead of master.

---

So, do you have a master one?
Am i helping you? Sorry if i understood wrong.

**Comment by abhi18av** [comment]
I apologize @sergiokopplin for the late reply, something came up and time flew)

So, I've experimented and after changing to `master` instead of `gh-branch` the site is being served https://abhi18av.github.io/resume/

But what I wish, is to have it served under the Project catalog in the template so how can I go from 
https://abhi18av.github.io/resume/  --->>>   https://abhi18av.github.io/projects/resume/.

How to setup the config file or some such change?
