### ISSUE TITLE
Change instructions to be "jekyll-now" like

### ISSUE THREAD

**Issue by renatogalvones** [sergiokopplin/indigo#171]
First of all, congratz on this amazing work, dude!

I think it would be more user friendly if Indigo was already up and running asap.

So, here's my suggestion/reference:

https://github.com/barryclark/jekyll-now

**Comment by sergiokopplin** [comment]
Nice suggestion. 

I'll read that to apply on indigo! Seems to be great!

Can you help on a pull request?

**Comment by renatogalvones** [comment]
This week is a little messy for me. I think I can work on something on the next one.

**Comment by sergiokopplin** [comment]
help wanted!

**Comment by sergiokopplin** [comment]
yeah, i was looking for that and requires a lot of work. not doing :/
