### ISSUE TITLE
ReOpened :: Unable to setup projects (URL clash perhaps )? 

### ISSUE THREAD

**Issue by abhi18av** [sergiokopplin/indigo#172]
@sergiokopplin , I felt I should reopen the issue https://github.com/sergiokopplin/indigo/issues/170 as the problem hasn't been solved yet. Please respond, so as to what I should do next to have the URLs setup properly.

The page is served under`abhi18av/resume`

whereas, I want it to be served under `abhi18av/projects/resume`

Thanks :)

**Comment by sergiokopplin** [comment]
![image](https://cloud.githubusercontent.com/assets/2743180/19225223/65e384ca-8e6e-11e6-9b95-4779a1d88e94.png)

---

![image](https://cloud.githubusercontent.com/assets/2743180/19225225/70488a00-8e6e-11e6-96c7-19726e909bc4.png)

---

![image](https://cloud.githubusercontent.com/assets/2743180/19225228/7c19d4d8-8e6e-11e6-9eae-630288829374.png)

---

is that what you're looking for?

**Comment by abhi18av** [comment]
Hmm, something similar.

Actually, I need to understand how does the project section really work?

Should I use a different tag to make jekyll count it as a project and populate the ~/projects webpage on the site? And, could you please also tell me whether I can add more permalinks like that in the same file `about.md` ?

**Comment by sergiokopplin** [comment]
@abhi18av sorry for the delay. i'll take a look this week.

**Comment by sergiokopplin** [comment]
the permalinks is how the page are rendered in the urls.
i guess you don't have to use tags for that.
could I help you?
