### ISSUE TITLE
Embedding link in bio?

### ISSUE THREAD

**Issue by aniellodesanto** [sergiokopplin/indigo#175]
Hi,

before bothering you with this stupid issue, let me thank you for this beautiful template :) 

Now, I am trying to add a link in my bio, but this results in some of it wrongfully showing up at the top of every page (apart from being correctly embedded in the home bio).
For example, if I add (I might be doing this wrong):

`<a class="link" href="https://github.com/sergiokopplin/indigo">Indigo theme</a>`

Into my bio, then **Indigo theme** will appear under my title as a working link, but also in the top left corner of every page i can see 

`Indigo theme.">` in light grey.

I understood how to fix it "manually" in each index page after the build, but I can't figure out what is happening. I am a novice to Jekyll and I tried reading around and studying your code carefully, but I still couldn't figure it our. Can you help?

Thanks in advance!

**Comment by sergiokopplin** [comment]
can you show me the code?
take a look [here](https://github.com/sergiokopplin/sergiokopplin.github.io).
is that helping?

**Comment by maximilianigl** [comment]
I just had the same problem. Replace all double quotes (") in the links with single quotes ('). Then it works.

**Comment by sergiokopplin** [comment]
@aniellodesanto can you check that solution? thank you @maximilianigl
