### ISSUE TITLE
There is no Stackoverflow icon in social-links

### ISSUE THREAD

**Issue by kamwysoc** [sergiokopplin/indigo#176]
Could you provide stackoverflow icon in icons.html?

http://stackapps.com/questions/347/svg-versions-of-the-logos

http://stackoverflow.com/company/logos

I've tried to paste this code 

https://jsfiddle.net/902d7bxc/

to icons.html but the icon not showing.

<img width="741" alt="screen shot 2016-10-16 at 10 44 56" src="https://cloud.githubusercontent.com/assets/9297748/19416301/acf82fcc-938d-11e6-9b90-58872dfe8997.png">

Thanks!

**Comment by rowmatrix** [comment]
@sergiokopplin @k8mil I created a pull request to solve this issue

**Comment by sergiokopplin** [comment]
@rowmatrix the build is broken, can you fix that?

![image](https://cloud.githubusercontent.com/assets/2743180/19532815/1aacbe26-961c-11e6-8bfd-61fff5e12f64.png)

**Comment by rowmatrix** [comment]
Alright will do!

**Comment by sergiokopplin** [comment]
We must have a valid link to stackoverflow, maybe some default profile

**Comment by rowmatrix** [comment]
Ok link should point to http://stackoverflow.com/users/7044681/mystackoverflow in new PR
