### ISSUE TITLE
Table support in .md?

### ISSUE THREAD

**Issue by cyfyifanchen** [sergiokopplin/indigo#177]
I tried to insert a table with .md, didn't seem working. Any ideas what's going on?

**Comment by sergiokopplin** [comment]
can you show me your code?

**Comment by cyfyifanchen** [comment]
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

I grabbed this piece of code from the markdown cheatsheet, I don't think this Tablet support is working in Indigo.

**Comment by sergiokopplin** [comment]
yeah, you're right!
we should put some table css on indigo.
can you create a PR for that?

**Comment by cyfyifanchen** [comment]
I just read the cheatsheet again, looks like table is only being supported at Github-flavored Markdown. I will see what I can do.

**Comment by sergiokopplin** [comment]
Ok them! i'll close that for now, you can reopen later if you want
