### ISSUE TITLE
tags.html

### ISSUE THREAD

**Issue by CodeMaxx** [sergiokopplin/indigo#180]
Currently `tags.html` shows tags only for posts. If I add another "collection" I am unable to get tags from them currently. Is there a simple way to do that?

**Comment by sergiokopplin** [comment]
i don't think so.
can you explain your final result for that?

**Comment by CodeMaxx** [comment]
So see on my webpage [http://codemaxx.github.io/writeups/](http://codemaxx.github.io/writeups/) . The tags on the posts here do not appear on the tags page. Only those in Blogs and projects do. I want a similar thing for writeups. Like posts are accessed using `site.posts`, these are accessed using `site.writeups`

**Comment by CodeMaxx** [comment]
@sergiokopplin Ping

**Comment by sergiokopplin** [comment]
hey @CodeMaxx, i'll check this today to answer you, but i think you can do

**Comment by sergiokopplin** [comment]
sorry @CodeMaxx for the delay.
are you still having problems?

**Comment by CodeMaxx** [comment]
Yes not resolved yet. @sergiokopplin

**Comment by sergiokopplin** [comment]
Hey @CodeMaxx, sorry for the delay.

---

Yeah, it's not easy to implement that, but it's possible.
Jekyll uses tags only for blog posts, not for other kind of documents, so it's not by default on jekyll.
You have to create by yourself the file.prop, then the page list, than the mapping system to show only writeups with some kind of props.

--- 

ps: i might be wrong, long time from my last jekyll documentation read.
