### ISSUE TITLE
Stackoverflow icon

### ISSUE THREAD

**Issue by kamwysoc** [sergiokopplin/indigo#181]
@rowmatrix 
You've done great work but one rectangle in stackoverflow icon is missing. I think it would be nice to fix it and provide proper logo :)

4 rectangles :
![screen shot 2016-10-20 at 16 10 58](https://cloud.githubusercontent.com/assets/9297748/19563330/d58107d4-96df-11e6-93ad-371ea68eaaf9.png)

5 rectangles :
![screen shot 2016-10-20 at 16 11 07](https://cloud.githubusercontent.com/assets/9297748/19563344/d9e710e8-96df-11e6-82d5-24f7c0cffd20.png)

Thanks!

**Comment by sergiokopplin** [comment]
is that right @rowmatrix ?

**Comment by rowmatrix** [comment]
Nice catch! I didn't notice that icomoon provides two stackoverflow icons
I'll fix it in a new PR

**Comment by sergiokopplin** [comment]
thank you @k8mil and @rowmatrix. really nice catch!

**Comment by rowmatrix** [comment]
<img width="548" alt="screen shot 2016-10-20 at 9 58 12 am" src="https://cloud.githubusercontent.com/assets/12551294/19569865/297d8fe4-96ac-11e6-92d7-332b7d3b2777.png">

@k8mil @sergiokopplin  Ok should be good now

**Comment by sergiokopplin** [comment]
thanks @rowmatrix. you are fast!!! 😄

**Comment by kamwysoc** [comment]
@rowmatrix cool!
Thanks!
