### ISSUE TITLE
Adding more share links 

### ISSUE THREAD

**Issue by rowmatrix** [sergiokopplin/indigo#183]
At the moment we have Twitter and Facebook share links in `author.html`. I've been working on adding other share links such as Google+ and LinkedIn. 
<img width="836" alt="google-plus-share" src="https://cloud.githubusercontent.com/assets/12551294/19575591/48e34f0a-96c4-11e6-878b-44b896743298.png">
<img width="828" alt="linkedin-share" src="https://cloud.githubusercontent.com/assets/12551294/19575597/4ee1b522-96c4-11e6-9c32-3ee0da3ec9e5.png">
<img width="823" alt="reddit-share" src="https://cloud.githubusercontent.com/assets/12551294/19575608/5649a112-96c4-11e6-9493-0b5e1b0b4312.png">

I should note that adding a third share link only works when the site's width is **large**. However, the user can choose to keep the site width on normal and choose any of the two: Twitter, Facebook, Google+, LinkedIn, and Reddit. 

If you like the idea I can submit a pull request. What do you think?

**Comment by sergiokopplin** [comment]
Yeah! That's great man! Make the PR, please :)

**Comment by sergiokopplin** [comment]
Thank you @rowmatrix
