### ISSUE TITLE
All but one social links icons appear in the header

### ISSUE THREAD

**Issue by pratik1105** [sergiokopplin/indigo#187]
First of all, thank you for this wonderful Minimalist Theme. I have been customizing it for a while and lately I have noticed that on reloading the "blog" page, all but one(instagram) social link icons appear. 
![indigo_issue](https://cloud.githubusercontent.com/assets/9898287/20837466/2f4328ea-b8ca-11e6-81d5-1a3383f96fde.png). 
In the image, there should be an instagram icon where there seems to be a blank space. The link still works though.
Upon reloading a couple of times, all icons reappear again. 
 
Any idea what could possibly be causing it ?

**Comment by sergiokopplin** [comment]
thank for the issue.

---

this is an old problem, and i still don't know why this happens. :/
do you have any idea?

**Comment by pratik1105** [comment]
Not yet. I'll let you know if I find the cause and/or the solution.

**Comment by sergiokopplin** [comment]
thanks @pratik1105. this is not solved yet, i'm also looking for it.
