### ISSUE TITLE
Include a resumé section

### ISSUE THREAD

**Issue by jayrav13** [sergiokopplin/indigo#188]
Hello,

I thought it would be cool to have a resumé section available in the template. Maybe two or three variables in the `_config.yml` file?

Example:

```yaml
resume-include: true
resume-url: /assets/resume.pdf
```

This can be included in the `navbar`. Looking forward to feedback - I should be able to submit a pull request shortly!

**Comment by sergiokopplin** [comment]
hey @jayrav13, thanks!

---

yeah, this seems to be a really good idea, can you implement that? thanks!

**Comment by jayrav13** [comment]
@sergiokopplin great! Sure, working on it now, will open a PR shortly.

**Comment by jayrav13** [comment]
@sergiokopplin PR #201 has been opened to address this proposed feature.

Thanks!

**Comment by sergiokopplin** [comment]
Thank you!
