### ISSUE TITLE
HTML style

### ISSUE THREAD

**Issue by Gorbyy** [sergiokopplin/indigo#194]
Hey, thanks for your work on this template! Is it normal to have the section <style> on the view-source:http://koppl.in/indigo/ so big? Specially if it looks like it was commented. Forgive me if I don't know what I talking about, I'm just learning :)

`<style> ﻿/*! normalize.css v4.1.1 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block}audio:not([controls]){display:none;height:0}progress{vertical-align:baseline}template,[hidden]{display:none}a{background-color:transparent;-webkit-text-decoration-skip:objects}a:active,a:hover{outline-width:0}abbr[title]{border-bottom:none;text-decoration:underline;text-decoration:underline dotted}b,strong{font-weight:inherit}b,strong{font-weight:bolder}dfn{font-style:italic}h1{font-size:2em;margin:0.67em 0}mark{background-color:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-0.25em}sup{top:-0.5em}img{border-style:none}svg:not(:root){overflow:hidden}code,kbd,pre,samp{font-family:monospace, monospace;font-size:1em}figure{margin:1em 40px}hr{box-sizing:content-box;height:0;overflow:visible}button,input,select,textarea{font:inherit;margin:0}optgroup{font-weight:bold}button,input{overflow:visible}button,select{text-transform:none}button,html [type="button"],[type="reset"],[type="submit"]{-webkit-appearance:button}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner{border-style:none;padding:0}button:-moz-focusring,[type="button"]:-moz-focusring,[type="reset"]:-moz-focusring,[type="submit"]:-moz-focusring{outline:1px dotted ButtonText}fieldset{border:1px solid #c0c0c0;margin:0 2px;padding:0.35em 0.625em 0.75em}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal}textarea{overflow:auto}[type="checkbox"],[type="radio"]{box-sizing:border-box;padding:0}[type="number"]::-webkit-inner-spin-button,[type="number"]::-webkit-outer-spin-button{height:auto}[type="search"]{-webkit-appearance:textfield;outline-offset:-2px}[type="search"]::-webkit-search-cancel-button,[type="search"]::-webkit-search-decoration{-webkit-appearance:none}::-webkit-input-placeholder{color:inherit;opacity:0.54}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}.highlight .c{color:#998;font-style:italic}.highlight .err{color:#a61717;background-color:#e3d2d2}.highlight .k{font-weight:bold}.highlight .o{font-weight:bold}.highlight .cm{color:#998;font-style:italic}.highlight .cp{color:#999;font-weight:bold}.highlight .c1{color:#998;font-style:italic}.highlight .cs{color:#999;font-weight:bold;font-style:italic}.highlight .gd{color:#000;background-color:#fdd}.highlight .gd .x{color:#000;background-color:#faa}.highlight .ge{font-style:italic}.highlight .gr{color:#a00}.highlight .gh{color:#999}.highlight .gi{color:#000;background-color:#dfd}.highlight .gi .x{color:#000;background-color:#afa}.highlight .go{color:#888}.highlight .gp{color:#555}.highlight .gs{font-weight:bold}.highlight .gu{color:purple;font-weight:bold}.highlight .gt{color:#a00}.highlight .kc{font-weight:bold}.highlight .kd{font-weight:bold}.highlight .kn{font-weight:bold}.highlight .kp{font-weight:bold}.highlight .kr{font-weight:bold}.highlight .kt{color:#458;font-weight:bold}.highlight .m{color:#099}.highlight .s{color:#d14}.highlight .n{color:#333}.highlight .na{color:teal}.highlight .nb{color:#0086b3}.highlight .nc{color:#458;font-weight:bold}.highlight .no{color:teal}.highlight .ni{color:purple}.highlight .ne{color:#900;font-weight:bold}.highlight .nf{color:#900;font-weight:bold}.highlight .nn{color:#555}.highlight .nt{color:navy}.highlight .nv{color:teal}.highlight .ow{font-weight:bold}.highlight .w{color:#bbb}.highlight .mf{color:#099}.highlight .mh{color:#099}.highlight .mi{color:#099}.highlight .mo{color:#099}.highlight .sb{color:#d14}.highlight .sc{color:#d14}.highlight .sd{color:#d14}.highlight .s2{color:#d14}.highlight .se{color:#d14}.highlight .sh{color:#d14}.highlight .si{color:#d14}.highlight .sx{color:#d14}.highlight .sr{color:#009926}.highlight .s1{color:#d14}.highlight .ss{color:#990073}.highlight .bp{color:#999}.highlight .vc{color:teal}.highlight .vg{color:teal}.highlight .vi{color:teal}.highlight .il{color:#099}.highlight .gc{color:#999;background-color:#EAF2F5}body,html{font-size:62.5%}body{line-height:1;font:16px "Helvetica Neue",Helvetica,Arial,sans-serif;color:#666}h1,h2,h3,h4{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;color:#222;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}h1{font-size:3rem;letter-spacing:-1px;color:#222;font-weight:700}h2{font-size:2.2rem}h3{font-size:2rem}h4{font-size:1.6rem}a{color:indigo;text-decoration:underline}p{line-height:1.7;color:#666;font-weight:300;margin-bottom:20px;letter-spacing:.4px}@media only screen and (max-width: 400px){p{letter-spacing:.2px}}strong{font-weight:400;color:#000}ul li,ol li{line-height:2.4rem;font-weight:300;color:#666}img,pre,iframe{max-width:100%}img,pre{border-radius:4px}figcaption{position:relative;top:-20px;left:0;right:0;margin:0 auto;width:100%;text-align:center;font-size:1.3rem;color:#aaa;font-weight:300}@media only screen and (max-width: 400px){figcaption{font-size:1.2rem}}blockquote{padding-left:15px;border-left:3px solid #eee}hr{border:none;height:1px;margin:40px auto;background:#eee;width:100%}figure.highlight{width:100%;margin:0}code,tt{padding:1px 0;font-family:"Consolas",Liberation Mono,Menlo,Courier,monospace;font-size:12px;line-height:20px;background:#fff;border-radius:2px;border-radius:2px}pre{box-sizing:border-box;margin:0 0 1.75em 0;width:100%;padding:5px 10px;font-family:"Consolas",Liberation Mono,Menlo,Courier,monospace;font-size:1.2rem;line-height:2rem;overflow:auto;background:#fff;border:1px solid #ededed;border-radius:2px}.wrapper-normal,.wrapper-large{height:100%;width:96%;margin:0 auto}@media only screen and (max-width: 400px){.wrapper-normal,.wrapper-large{width:88%}}@media only screen and (min-width: 400px) and (max-width: 1050px){.wrapper-normal,.wrapper-large{width:88%}}.wrapper-normal{max-width:560px}.wrapper-large{max-width:810px}.text-center{text-align:center}.clearfix:before,.clearfix:after{content:"";display:table}.clearfix:after{clear:both}.animated{animation:fade-in-down .6s;animation-delay:.3s;animation-fill-mode:both}@keyframes fade-in-down{0%{opacity:0;transform:translateY(-10px)}100%{opacity:1;transform:translateY(0)}}.home,.blog,.projects{margin-top:125px}.home>.list,.blog>.list,.projects>.list{border-top:1px solid #ededed;margin-top:30px;padding-top:40px;position:relative}.home>.list:before,.blog>.list:before,.projects>.list:before{display:block;content:" ";width:7px;height:7px;border:#ededed 1px solid;position:absolute;top:-5px;left:50%;margin-left:-5px;background:#FFF;box-shadow:#FFF 0 0 0 5px;border-radius:3px}.home>.list>.item,.blog>.list>.item,.projects>.list>.item{display:block;width:95%;margin:0 auto}.home>.list>.item>.url,.blog>.list>.item>.url,.projects>.list>.item>.url{width:100%;display:block;padding:20px 0;text-decoration:none}.home>.list>.item>.url>.title,.blog>.list>.item>.url>.title,.projects>.list>.item>.url>.title{margin:0;width:75%;font-weight:500;transition:all ease-in-out .2s}.home>.list>.item:hover>.url>.title,.blog>.list>.item:hover>.url>.title,.projects>.list>.item:hover>.url>.title{color:indigo}.home>.list aside,.blog>.list aside,.projects>.list aside{position:relative;top:2px;margin:0;width:25%;float:right;font-weight:300;color:#aaa;text-align:right;transition:all ease-in-out .2s}.home>.list .item:hover .url aside,.blog>.list .item:hover .url aside,.projects>.list .item:hover .url aside{color:#666}.projects>.list>.item>.url>.title{display:inline}.projects>.list>.item>.url>.emoji{display:inline;position:relative;top:-4px;margin-right:10px}.page{margin-top:125px}.page>h1{text-align:center;margin-bottom:6rem}.about img{width:50%;margin:0 auto;display:block}.post{margin-top:125px}.post>.title{text-align:center;margin-bottom:3rem}.post>.date,.post>.post-tags{color:#aaa;font-weight:300;font-size:1.4rem;text-transform:uppercase;text-align:center;display:block;margin-bottom:6rem;letter-spacing:1px;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}.post>.date{margin-bottom:2rem}.post>.post-tags>.item{padding:2px 8px;border-radius:3px;font-size:1.1rem;background:#ededed;color:#666;letter-spacing:1px;margin:3px 1px;text-decoration:none;display:inline-block}.post>h2,.post>h3,.post>h4{margin-top:40px}.post>h2 a,.post>h3 a,.post>h4 a{text-decoration:none}.post>.title-image{max-height:120px;display:block;margin:0 auto}.post>.blog-navigation{font-size:1.4rem;display:block;width:auto;overflow:hidden}.post>.blog-navigation a{display:block;width:50%;float:left;margin:1em 0}.post>.blog-navigation .next{text-align:right}.tags{margin-top:125px}.tags>.list{border-top:1px solid #ededed;margin-top:30px;padding-top:40px;position:relative}.tags>.list:before{display:block;content:" ";width:7px;height:7px;border:#ededed 1px solid;position:absolute;top:-5px;left:50%;margin-left:-5px;background:#FFF;box-shadow:#FFF 0 0 0 5px;border-radius:3px}.tags>.list>.item{font-weight:300;text-transform:uppercase;text-align:center;margin-bottom:6rem;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;padding:3px 9px;border-radius:3px;font-size:1.3rem;background:#ededed;color:#666;letter-spacing:1px;margin:0 .5rem 1rem;text-decoration:none;display:inline-block}.tag-list>.list{padding:0}.tag-list>.list>.item{display:block;width:80%;margin:0 10%}.tag-list>.list>.item>.url{width:100%;height:100%;display:block;padding:20px 0;text-decoration:none}.tag-list>.list>.item>.url>.title{margin:0;width:75%;font-weight:400;transition:all ease-in-out .2s;font-size:1.6rem}.tag-list>.list>.item:hover>.url>.title{color:indigo}.tag-list>.list aside{position:relative;top:2px;margin:0;width:25%;float:right;font-weight:300;color:#aaa;text-align:right;transition:all ease-in-out .2s;font-size:1.6rem}.tag-list>.list .item:hover .url aside{color:#666}.author{padding:3rem 0;border-bottom:1px solid #ededed;border-top:1px solid #ededed;max-width:100%;margin:4rem auto 0}.author>.toleft>.selfie{width:90%;border-radius:100%}.author>.toright>.name,.author>.toright>.bio{width:60%;display:inline-block}.author>.toright>.name{font-size:1.5rem;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-weight:500;margin:6px 0 0}@media only screen and (max-width: 400px){.author>.toright>.name{width:100%;display:block}}@media only screen and (min-width: 400px) and (max-width: 1050px){.author>.toright>.name{width:100%;display:block}}.author>.toright>.bio{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-weight:300;color:#aaa;font-size:1.3rem;text-align:justify;line-height:1.5;margin:0}@media only screen and (max-width: 400px){.author>.toright>.bio{width:100%;display:block}}@media only screen and (min-width: 400px) and (max-width: 1050px){.author>.toright>.bio{width:100%;display:block}}.author>.toleft{width:10%;display:inline-block}@media only screen and (max-width: 400px){.author>.toleft{width:20%}}@media only screen and (min-width: 400px) and (max-width: 1050px){.author>.toleft{width:20%}}.author>.toright{width:89%;display:inline-block;vertical-align:top}@media only screen and (max-width: 400px){.author>.toright{width:78%}}@media only screen and (min-width: 400px) and (max-width: 1050px){.author>.toright{width:78%}}.no-disqus{border-bottom:none;padding-bottom:0}.disqus{margin:0 auto;max-width:100%;padding:40px 0}.footer-main{border-top:1px solid #ededed;padding:40px 0;margin:40px 0 0;font-size:1.3rem;color:#aaa;font-weight:300;text-align:center;position:relative}.footer-main:before{display:block;content:" ";width:7px;height:7px;border:#ededed 1px solid;position:absolute;top:-5px;left:50%;margin-left:-5px;background:#FFF;box-shadow:#FFF 0 0 0 5px;border-radius:3px}.footer-main>.link{display:inline}.footer-main>.link>.icon{width:15px !important;fill:#aaa !important;transition:ease-in-out all .3s;position:relative;top:3px;display:inherit;margin:0}.footer-main>.link>.icon:hover{fill:indigo !important}.footer-main>.extra{color:#aaa;margin-top:0}.footer-main>.extra>.link{color:#222;text-decoration:none;border-bottom:1px solid transparent;transition:ease-in-out all .3s;padding-bottom:1px}.footer-main>.extra>.link:hover{border-color:#aaa}.header-home{display:block;margin:0 auto;text-align:center;position:relative;z-index:99}.header-home>.link>.selfie{width:125px;margin-bottom:25px;border-radius:100%;transition:all .2s;box-shadow:0;opacity:1}.header-home>.link>.selfie:hover{box-shadow:0 0px 4px 0 rgba(0,0,0,0.18),0 0px 12px 0 rgba(0,0,0,0.15);opacity:.8}.header-home>.title{font-size:4rem;margin:0 0 13px}.header-home>.description{font-size:1.85rem;font-weight:300;font-style:normal;color:#aaa;width:70%;margin:0 auto 30px}.header-home>.description a{font-weight:200}.nav>.list,.nav-home>.list{list-style:none;margin:0;padding:0 13px 0}.nav>.list>.item,.nav-home>.list>.item{display:inline-block}.nav>.list>.item>.link,.nav-home>.list>.item>.link{display:inline-block;font-weight:300;font-size:1.4rem;padding:20px 10px;text-decoration:none}.nav{position:absolute;right:0;top:0}.nav>.list{padding:0 13px 0}.nav>.list>.item>.link{font-size:1.4rem;padding:20px 10px}.nav-home{margin-top:40px;text-align:center}.nav-home>.list{padding:0}.nav-home>.list>.item>.link{font-size:2rem;padding:7px 15px;margin:0;border-radius:4%;transition:all .4s ease-in-out;width:70px}.nav-home>.list>.item>.link:hover{color:#666}.evidence{background-image:linear-gradient(to bottom, rgba(39,243,106,0.15), rgba(39,243,106,0.15));color:beta}.star>.url>.title{width:auto !important;display:inline;background-image:linear-gradient(rgba(39,243,106,0.15), rgba(39,243,106,0.15))}.twitter-tweet{margin:10px auto}.icon{display:inline-block;width:17px;height:17px;fill:#000;text-align:center;color:#000;margin:7px auto}.caption{position:relative;top:1rem;left:0;right:0;margin:0 auto;width:100%;text-align:center;font-size:1.3rem}.bigger-image{min-width:130%;margin:5rem 0 5rem -15%}@media only screen and (max-width: 400px){.bigger-image{min-width:114%;margin:2rem 0 2rem -7%}}@media only screen and (min-width: 400px) and (max-width: 1050px){.bigger-image{min-width:114%;margin:2rem 0 2rem -7%}}.breaker{height:1px;margin:6rem auto;width:100%}.breaker:before{content:"• • •";width:100%;text-align:center;display:block;color:#aaa;letter-spacing:4px;position:relative;top:-8px}.pagination{width:95%;margin:3rem auto 0;text-align:center}.pagination>.page_number{display:inline-block;font-size:1.3rem}.pagination>.previous,.pagination>.next{display:inline-block;font-size:1.8rem;position:relative;top:1px;padding:1px 9px}.pagination>.hidden{visibility:hidden}.related{margin:10rem 0 0rem}.share{float:right;width:40%;display:inline;text-align:right;position:relative;top:-10px}@media only screen and (max-width: 400px){.share{width:100%;display:block;top:0;text-align:left;float:none;margin-top:5px}}@media only screen and (min-width: 400px) and (max-width: 1050px){.share{width:100%;display:block;top:0;text-align:left;float:none;margin-top:5px}}.share>.twitter,.share>.facebook,.share>.google-plus,.share>.linkedin,.share>.reddit{display:inline;vertical-align:middle;font-size:13px;font-weight:700;color:#fff;padding:6px 10px;border-radius:3px;margin-left:5px;text-decoration:none}@media only screen and (max-width: 400px){.share>.twitter,.share>.facebook,.share>.google-plus,.share>.linkedin,.share>.reddit{margin:0 5px 10px 0}}@media only screen and (min-width: 400px) and (max-width: 1050px){.share>.twitter,.share>.facebook,.share>.google-plus,.share>.linkedin,.share>.reddit{margin:0 5px 10px 0}}.share>.twitter{background:#4fafed}.share>.facebook{background:#4361b3}.share>.google-plus{background:#dd4b39}.share>.linkedin{background:#0077b5}.share>.reddit{background:#ff4500}.share svg{fill:#fff;position:relative;top:3px;margin:0;margin-right:4px;display:inherit}@media only screen and (min-width: 780px){.side-by-side{width:130%;margin:6rem 0 6rem -15%}}@media only screen and (max-width: 780px){.side-by-side{width:100%;margin:4rem 0}}.side-by-side>.toleft,.side-by-side>.toright{display:inline-block;width:47.5%}@media only screen and (max-width: 780px){.side-by-side>.toleft img,.side-by-side>.toright img{text-align:center;display:block;margin:0 auto}}@media only screen and (min-width: 780px){.side-by-side>.toleft{margin-right:2%}}@media only screen and (max-width: 780px){.side-by-side>.toleft{width:100%;margin:0 0 4rem 0}}@media only screen and (min-width: 780px){.side-by-side>.toright{margin-left:2%;vertical-align:top}}@media only screen and (max-width: 780px){.side-by-side>.toright{width:100%;margin:0 0 4rem 0}}.side-by-side>.toleft>p,.side-by-side>.toright>p{margin:0 0 4rem 0}@media only screen and (max-width: 780px){.side-by-side>.toleft>p,.side-by-side>.toright>p{margin:0}}.social-links{margin-top:20px}.social-links>.link{margin:0;text-decoration:none;position:relative;display:inline-block;height:35px;width:35px}.social-links>.link:hover>.icon{fill:indigo}.social-links>.link:hover:before{opacity:1;transform:translate3d(0, 0, 0);white-space:nowrap}.social-links>.link:before{content:attr(data-title);display:inline-block;position:absolute;bottom:-34px;left:-6px;margin:0 auto;font-size:13px;padding:3px 10px;background:#222;color:#fff;border-radius:2px;height:22px;line-height:22px;opacity:0;transition:opacity 150ms linear,transform 150ms linear,-webkit-transform 150ms linear;transform:translate3d(0, -8px, 0);z-index:99}.social-links>.link:after{content:"";position:absolute;top:35px;left:13px;width:0;height:0;border-left:5px solid transparent;border-right:5px solid transparent;border-bottom:6px solid #222;opacity:0;transition:opacity 150ms linear,transform 150ms linear,-webkit-transform 150ms linear;transform:translate3d(0, -8px, 0);z-index:100}.social-links>.link:hover:after{opacity:1;transform:translate3d(0, 0, 0)}.social-links>.icon{transition:all ease-in-out .2s}.spoiler{position:relative}.spoiler:before{content:"";background-color:#fafae0;position:absolute;top:0;bottom:0;left:0;right:0;z-index:50}.spoiler:hover:before{display:none} </style>`

**Comment by sergiokopplin** [comment]
Thanks for the issue.

---

Yeah, it seems big, that's true.
This idea of inline css is based on a google [project](https://developers.google.com/speed/pagespeed/insights/?hl=pt-BR).
It has the entire css page for all the pages, which is not too much (+/- 18kb).

If you have any problem, tell me.
