### ISSUE TITLE
Facebook Icon Href adding a dot '.' between First and Last Name

### ISSUE THREAD

**Issue by bradstimpson** [sergiokopplin/indigo#195]
Hello,
For some unknown reason, the URL for the facebook icon is being modified to include a dot '.' between the first and last name.

In _config.yml it is configured as:
`facebook: firstnamelastname`
and when I hover over the icon I see the correct URL:
`facebook.com/firstnamelastname`
but when the icon is clicked, this is the URL that is opened in the browser:
`https://www.facebook.com/firstname.lastname'
In my case this goes to a 404 page.

@sergiokopplin Is this a configuration issue or is there an assumption that everyone has a public facebook page with a dot between first and last name?

**Comment by bradstimpson** [comment]
To add a little more color to this issue, it only occurs in Firefox (I am using 50.1.0) on Linux Mint.  It does not occur in Google Chrome on Win10.

**Comment by sergiokopplin** [comment]
Thanks for the issue.

---

This is not supposed to happen due to this code:

```
{% if site.facebook %}
        <a class="link" data-title="facebook.com/{{ site.facebook }}" href="http://facebook.com/{{ site.facebook }}" target="_blank">
            <svg class="icon icon-facebook"><use xlink:href="#icon-facebook"></use></svg>
        </a>
{% endif %}
```

---

it don't include any dots in the url, so this seems to be a different problem, not related to the indigo project itself.
