### ISSUE TITLE
Missing title image file for indigo project page

### ISSUE THREAD

**Issue by jehartzog** [sergiokopplin/indigo#204]
On your demo site, the [project page](https://koppl.in/indigo/indigo-jekyll-theme/) is missing the title image.

![image](https://cloud.githubusercontent.com/assets/14143246/22186771/1a223ea2-e0c9-11e6-82a2-035edae34a37.png)

I would like to fix it with a PR, but I built your branch and it seemed to work fine, so you probably need to just rebuild for your demo site.

![image](https://cloud.githubusercontent.com/assets/14143246/22186781/5375ed52-e0c9-11e6-8b02-49f9fec70566.png)

**Comment by sergiokopplin** [comment]
Thanks for that! Yeah, not working, don't know why, the file is there. Maybe with a new build. Testing this later!

**Comment by sergiokopplin** [comment]
[solved](https://github.com/sergiokopplin/indigo/commit/a60fd6ae337691fd861f838aee1f5d670b9995fe)
