### ISSUE TITLE
`hidden: true` is not hiding a post from the blog section. 

### ISSUE THREAD

**Issue by jamesstonehill** [sergiokopplin/indigo#208]
If I'm understanding the intention correctly, the selected line in the image below should hide the project post from the blog section, but it is not doing that correctly. 

<img width="844" alt="screen shot 2017-01-31 at 15 53 56" src="https://cloud.githubusercontent.com/assets/19637233/22472461/9c14fa02-e7cd-11e6-92f6-cfb9dd6e81fc.png">

**Comment by sergiokopplin** [comment]
Hey, sorry about the delay. Huge project going on here. I'll take o look on that later.

Thanks for reporting.

**Comment by jamesstonehill** [comment]
Hi @sergiokopplin. I've submitted a PR that fixes this issue. https://github.com/sergiokopplin/indigo/pull/209

**Comment by sergiokopplin** [comment]
fixed. thanks @jamesstonehill
