### ISSUE TITLE
Social icon links aren't ever "hidden"

### ISSUE THREAD

**Issue by ghost** [sergiokopplin/indigo#211]
This is regarding the social icons on pages (ie "blog" or "projects"). Right now, they're "invisible" (you can't see the icon), but you can still mouse over where the icons were and the link shows up.

**Comment by dbogdanov** [comment]
I got the same problem.

**Comment by sergiokopplin** [comment]
Hey guys, sorry about the delay. Huge project going on here. I'll take o look on that later.

Thanks for reporting.

**Comment by dbogdanov** [comment]
Update: I found that my uBlock Origin extension for firefox was blocking the icons.

**Comment by sergiokopplin** [comment]
Is that fixed then? Can you describe better?
Are you having this problem yet @9fiftyfive? Is your problem related to @dbogdanov description?

**Comment by ghost** [comment]
@sergiokopplin Sorry, but I no longer use the Indigo theme. The issues persisted in all browsers.

**Comment by sergiokopplin** [comment]
@dbogdanov 'ghost' is not a user anymore, can you help me with that? thanks

**Comment by sergiokopplin** [comment]
closing by inactivity
