### ISSUE TITLE
There is no feed.xml

### ISSUE THREAD

**Issue by SanketDG** [sergiokopplin/indigo#217]
`feed.xml` is not present in the project, its needed for rss feeds and planets

**Comment by vhbsouza** [comment]
@SanketDG  I've managed to fix it and submitted and pull request. #219

**Comment by sergiokopplin** [comment]
Hey guys, sorry about the delay. Huge project going on here. I'll take o look on that later.

Thanks for reporting.

**Comment by sergiokopplin** [comment]
My bad! Thanks @SanketDG and @vhbsouza

**Comment by sergiokopplin** [comment]
fixed #219
