### ISSUE TITLE
researchgate icon

### ISSUE THREAD

**Issue by FGhavamian** [sergiokopplin/indigo#220]
First of all, thanks for the pretty cool theme. 
I would like to make a researchgate (a social media for researchers) icon. I understand that there are a list of icons in _includes/icons.html which are basically some sort of codes. I would like to, for instance convert this image: https://www.researchgate.net/apple-touch-icon-180x180.png to a sort of code that is understandable for this theme.

**Comment by sergiokopplin** [comment]
@FariborzGh hey man!
Yes, we can add!

You need to put it [here](https://github.com/sergiokopplin/indigo/blob/gh-pages/_includes/icons.html).
Must be a svg code. You can search for that [here](https://icomoon.io/)

**Comment by FGhavamian** [comment]
Awesomeness to the whole new level, thanks!
For others who might be interested: I used [this](http://www.flaticon.com/free-icon/researchgate-logo_49051#term=researchgate&page=1&position=3) logo.

**Comment by sergiokopplin** [comment]
Great! Can you make a PR? thanks

**Comment by FGhavamian** [comment]
I would. I just do not quite know how to make a pull request for only one single file. I don't want to push my entire modifications through.

**Comment by sergiokopplin** [comment]
@FariborzGh any news?
