### ISSUE TITLE
Manifest required

### ISSUE THREAD

**Issue by abuxton** [sergiokopplin/indigo#226]
Themes now require manifest for install in jekyll 
$rake theme:install git=https://github.com/sergiokopplin/indigo.git
Cloning into './_theme_packages/_tmp'...
remote: Counting objects: 2019, done.
remote: Total 2019 (delta 0), reused 0 (delta 0), pack-reused 2019
Receiving objects: 100% (2019/2019), 2.85 MiB | 228.00 KiB/s, done.
Resolving deltas: 100% (1086/1086), done.
Checking connectivity... done.
rake aborted!
Errno::ENOENT: No such file or directory - ./_theme_packages/_tmp/manifest.yml
/Users/abuxton/src/abuxton.github.io/Rakefile:335:in `initialize'
/Users/abuxton/src/abuxton.github.io/Rakefile:335:in `open'
/Users/abuxton/src/abuxton.github.io/Rakefile:335:in `verify_manifest'
/Users/abuxton/src/abuxton.github.io/Rakefile:316:in `theme_from_git_url'
/Users/abuxton/src/abuxton.github.io/Rakefile:217:in `block (2 levels) in <top (required)>'
Tasks: TOP => theme:install
(See full trace by running task with --trace)

**Comment by sergiokopplin** [comment]
Thanks Man!
Do you know where i can find more documentation about it?

**Comment by sergiokopplin** [comment]
Closing by now
