### ISSUE TITLE
Twitter Card contains some errors

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#228]
Some of the Twitter tags for the blogposts contain errors. For example:

* Picture is missing when sharing on Twitter, but works fine on Facebook
* twitter:creator points to author name for the site, not the value set under twitter for that author (resulting in wrong value)

This might be something in the jekyll-seo-tag?

https://cards-dev.twitter.com/validator

**Comment by sergiokopplin** [comment]
@mehmandarov yeah, maybe some error with jekyll-seo-tag. I've removed the static code that was generating this piece of data, but seems to have a problem now. Have you tested without jekyll-seo-tag?

**Comment by mehmandarov** [comment]
@sergiokopplin: I checked that now. It is a bug in jekyll-seo-tag and can be fixed by updating Gemfile.lock.

**Comment by mehmandarov** [comment]
Reported to Jekyll SEO Tag: https://github.com/jekyll/jekyll-seo-tag/issues/210

**Comment by sergiokopplin** [comment]
closing for now.

**Comment by johnwmillr** [comment]
@mehmandarov, did you ever come up with a way to get this working? I've never been able to get Twitter to show the correct picture when I post a link to one of my blog posts. As you said, Facebook correctly identifies the post's image tag. I got Twitter to recognize a single site-wide image that is common to all of my posts, but of course I'd prefer if Twitter showed the image I've set as unique to the post.

**Comment by mehmandarov** [comment]
@johnwmillr Nope. Still living with this bug. Please let me know if you will find a solution to that problem.

**Comment by johnwmillr** [comment]
Okay, I'll see if I come up with something, but I'm not too hopeful...

**Comment by johnwmillr** [comment]
@mehmandarov, I may have solved this issue!

See my [latest commit](https://github.com/johnwmillr/johnwmillr.github.io/commit/536a024fe3e95b4b661a91f1b22e268c82760b40) for the changes that finally resolved the issue.

Key changes:
  - Change `post` to `page` within the `_includes/social-cards.html` file
  - Move the `{% include social-cards.html %}` line from `_layouts/post.html` to `_layouts/page.html`

You can use the Twitter [Card Validator](https://cards-dev.twitter.com/validator) to verify that post images are properly shared from my site. [This post](https://www.johnwmillr.com/interactive-plots-in-jekyll/) has a post image assigned (and is picked up by Twitter), whereas [this one](https://www.johnwmillr.com/unix-to-the-rescue/) does not and a default image is used.

Let me know if that works for you!
