### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by Rychillie** [sergiokopplin/indigo#231]
When activating pagination and determining number of posts, the navigation area is ok, but does not show posts. I could not identify the problem, because I only did a test of aesthetics.

**Comment by sergiokopplin** [comment]
I just accepted a pull request to fix this. Can you update your fork and test it again? Thanks

**Comment by Rychillie** [comment]
Now it does not show anything, returning to the old code, it does not show anything, it stays the same again... I will continue testing and I will modified code, see what I can do.

**Comment by sergiokopplin** [comment]
Any news on that?

**Comment by sergiokopplin** [comment]
Closing by now
