### ISSUE TITLE
What is the propose of .link &:before and &:after css classes ?

### ISSUE THREAD

**Issue by ravpacheco** [sergiokopplin/indigo#232]
Hello Sergio, 

what was your propose with **.link &:before** and **&:after** css classes (on social-links.sass)?
This classes make a little bug on mobile version. I don't know why but with this classes each social icon use a aditional space and the responsive page get a unecessary horizontal scroll.

![image](https://cloud.githubusercontent.com/assets/2591614/25787264/71201c60-3376-11e7-84a4-5b6af0027429.png)

*You can check this issue in my site ([ravpacheco.com](ravpacheco.com)) using mobile version.*

To fix this I removed this classes and everything worked fine. You really need this classes or can I send a pull request removing this things ?

**Note: This problem occur only with you enable a more than 6 social icon**

**Comment by sergiokopplin** [comment]
If i remember, it's used for this 'popup'.

![image](https://cloud.githubusercontent.com/assets/2743180/26026031/727a59ce-37ca-11e7-8684-bf23c19ea5ef.png)

**Comment by sergiokopplin** [comment]
Have you edited the code on this? Seems to be not working in your application.

**Comment by ravpacheco** [comment]
Yes @sergiokopplin , I removed this on my application and now the popup don't work. I will try to fix this without remove the popup and send to you the results. Tks :)

**Comment by sergiokopplin** [comment]
OK, sounds good!
Nice work with the translated content!

**Comment by ravpacheco** [comment]
Thank you. I'm trying to improve the translation process to proppose a pull request. As soon as I finish, I'll let you know.

**Comment by sergiokopplin** [comment]
Valeu mesmo!! Era exatamente isso que eu ia pedir!

**Comment by ravpacheco** [comment]
@sergiokopplin I did a pull request in order to fix this issue.

https://github.com/sergiokopplin/indigo/pull/234
