### ISSUE TITLE
Make picture a circle, not oval

### ISSUE THREAD

**Issue by mbbroberg** [sergiokopplin/indigo#233]
Quick question - What do I need to do to have my profile picture to be circular like [the demo](http://koppl.in/indigo/) as opposed to egg-shaped like [mine is now](https://mbbroberg.github.io/)? 

Thanks!

**Comment by sergiokopplin** [comment]
Your picture must be a square, like 1:1.
Can you update the picture?

**Comment by mbbroberg** [comment]
Oh that makes perfect sense! Updated and it works - thank you!!
