### ISSUE TITLE
How to change "Projects" to "Articles"

### ISSUE THREAD

**Issue by khantasha** [sergiokopplin/indigo#235]
Hi! Love your Jekyll theme! I'm a NOOB to Jekyll and I'm currently trying to change the navigation to from "Blog Projects About Resume" to say "About Articles Resume" ... can't figure out what file(s) to change this in, though? Can you help? Thanks!

**Comment by sergiokopplin** [comment]
I'll that a look later! :)

**Comment by khantasha** [comment]
Thanks! This noob appreciates the help!

**Comment by khantasha** [comment]
Hi sergio. I was wondering if you had a chance to address or answer this issue? Would really appreciate the help! Thank you from Pennsylvania!

**Comment by sergiokopplin** [comment]
Hey, i'm back. I was on vacation time.
I'll take a look this week.

**Comment by khantasha** [comment]
Thank you, thank you!

**Comment by jehartzog** [comment]
Rearrange and rename the links in `/_includes/nav.html`.

If you rename `Projects` to `Articles` and update the link, you will also need to rename `/projects.html`.

**Comment by sergiokopplin** [comment]
thanks @jehartzog
