### ISSUE TITLE
_config.yaml not updating

### ISSUE THREAD

**Issue by discentem** [sergiokopplin/indigo#239]
I'm running the site locally with `bundle exec jekyll serve --config _config.yml,_config-dev.yml --watch` but unfortunately not seeing the latest changes. For example, I still see the generic author bio. 

I am able to see update svg images though. 

Any ideas? Thanks in advance.

**Comment by discentem** [comment]
this might have been a silly mistake. Closing for now.

**Comment by sergiokopplin** [comment]
No problem! ask if you need
