### ISSUE TITLE
Recommend a comment system: Gitment

### ISSUE THREAD

**Issue by KiritoBeater** [sergiokopplin/indigo#241]
[Gitment](https://github.com/imsun/gitment), used Github issues, a good idea.

**Comment by sergiokopplin** [comment]
Have you implemented that?

**Comment by KiritoBeater** [comment]
Yep. See [Mine](https://kiritobeater.github.io/iOS系统自带调试悬浮窗/)

**Comment by sergiokopplin** [comment]
Can you implement that via pr?

**Comment by sergiokopplin** [comment]
Closing for now by inactivity.
