### ISSUE TITLE
Change display order of blog posts

### ISSUE THREAD

**Issue by johnsmith1212** [sergiokopplin/indigo#243]
Hi @sergiokopplin ,
how can I change the display order of the blog posts? I want to have the newest one at the top of the list. At the moment the oldest one is on first place. Cheers

**Comment by johnsmith1212** [comment]
Hi @sergiokopplin,
any change to take a look at this? Thx so much!

**Comment by jehartzog** [comment]
[solution](http://lmgtfy.com/?q=jekyll+post+order)

The first code snippet from the first answer is what you're looking for :D.

Edit:
For others who may have the same question, just add the `reversed `  keyword to the two for loops in `/blog/index.html`.
```
{% for post in site.posts reversed %}
```

**Comment by johnsmith1212** [comment]
@jehartzog Thank you so much! It works fine! Cheers

**Comment by sergiokopplin** [comment]
thanks @jehartzog
