### ISSUE TITLE
Color Inversion

### ISSUE THREAD

**Issue by jtroussard** [sergiokopplin/indigo#255]
This is just a feature request

Just wondering if it would be worthwhile to have a configuration option which inverts the color scheme, namely going from a white background/black text -> black background/white text. Not sure what kind of work would be involved or if it would affect the syntax highlighting but might be a good feature.

Thanks

**Comment by jehartzog** [comment]
If you wanted to make a PR for this it shouldn't be very difficult. Create the `.sass` files that make up your desired color scheme, and you would be able to add a option to `_config.yml` to adjust it.

To recognize that flag you'd need to edit [`_layouts/default.html`](https://github.com/sergiokopplin/indigo/blob/gh-pages/_layouts/default.html#L23) using the liquid syntax with an [if/else](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else) block to pick which style sheet to use.

Having the extra unused `.sass` files wouldn't matter too much, as only the files actually used will get packaged with the site.

**Comment by jtroussard** [comment]
Thanks for the feedback and advice. I'll take a crack at it tomorrow.

**Comment by sergiokopplin** [comment]
Closing for now by inactivity.
