### ISSUE TITLE
What do you think of implementing Instant View and Instant Articles?

### ISSUE THREAD

**Issue by Rychillie** [sergiokopplin/indigo#257]
[Instant View](instantview.telegram.org) and [Instant Articles](instantarticles.fb.com/) are ways to read pages on the web more quickly and smoothly, thus bringing a greater amount of access.

What do you think of implementing in Indigo?

**Comment by jehartzog** [comment]
I didn't look into extensive detail, but what benefit would adding those provide? This template is so streamlined and lightweight that my current page is DOMContentLoaded in ~70ms with complete loading done in ~180ms. There are FPS gamers who play with more latency than that!

Plus these services both involve needing to submit content to their services, meaning a good deal of extra steps, which I'm pretty sure can't be done automatically via GH-pages, for a some small gain.
