### ISSUE TITLE
Migrate icons from SVG to Font Awesome Icon

### ISSUE THREAD

**Issue by anirudhbiyani-zz** [sergiokopplin/indigo#259]
Better fonts, easily usable and quite large collection.
Font Awesome URL - http://fontawesome.io/icons/

**Comment by mehmandarov** [comment]
Great idea. Would you like to submit a pull request, @anirudhbiyani?

**Comment by sergiokopplin** [comment]
great idea @anirudhbiyani. can you help us?

**Comment by anirudhbiyani-zz** [comment]
@mehmandarov  would have submitted a pull request but I tried migrating to FA but some of the CSS broke for me, that is why I submitted this enhancement request. I am kind of new to Jekyll or Frontend Dev for that matter.

@sergiokopplin  yeah! would totally love to help wherever possible.

**Comment by mehmandarov** [comment]
@anirudhbiyani: Great! Try asking here. Pro tip would be attaching a patch file here, so we can reproduce the errors, and, maybe, we would be able to help you with errors. @sergiokopplin is a pro with Jekyll. 🥇

**Comment by anirudhbiyani-zz** [comment]
Created PR #262 

Let me know your thoughts on that.

**Comment by akhilesh-k** [comment]
Its a great idea, please do so. @sergiokopplin

**Comment by sergiokopplin** [comment]
Hey guys, i'll check it later, it seems great!

**Comment by sylvainmetayer** [comment]
Hi, is their any update on this ?

I've been working on a plugin to integrate Font Awesome, which I will be converting to a Gem when it will be finished but I'm stuck, my icon are properly generated but not displayed. 

You can see details of my [StackOverflow question](https://stackoverflow.com/questions/53540337/svg-not-displayed) and my [Work in progress here](https://github.com/sylvainmetayer/sylvainmetayer/pull/65)

**Comment by sergiokopplin** [comment]
there's a pr doing that, closing here for now
