### ISSUE TITLE
CSS not applied

### ISSUE THREAD

**Issue by ghost** [sergiokopplin/indigo#260]
I have cloned this repo and followed instruction as mentioned in readme. On localhost it is working fine but when I try to check on drashti4.github.io but It is not showing me css

For testing app 

> $bundle exec htmlproofer ./_site
`./_site/markdown-common-elements/index.html *  External link http://markitdown.net failed: got a time out (response code 0)`

**Comment by mehmandarov** [comment]
What errors do you get in the developer console of the browser? It seems to work fine for me. The `htmlproofer` error is due to the external link being not available. The test checks if all the links are accessible.

**Comment by mehmandarov** [comment]
I will be closing this issue, @drashti4, but you are welcome to reopen it when you have more info. :-)
