### ISSUE TITLE
Change Title names of Tabs

### ISSUE THREAD

**Issue by misaleh** [sergiokopplin/indigo#261]
Hi, 
How I can change the title of the tabs ? I want to remove the website name from it.
For ex here I want it to be "Blog" only

![screenshot from 2017-10-31 08-16-45](https://user-images.githubusercontent.com/17167881/32210072-4efe124e-be14-11e7-9e92-d7ea48aa5702.png)

and here, to be "Home" only

![screenshot from 2017-10-31 08-17-53](https://user-images.githubusercontent.com/17167881/32210076-5c291ec8-be14-11e7-9ed0-8d36d479a805.png)

**Comment by mehmandarov** [comment]
The title comes from [Jekyll CEO Tag][1]. You can read about customisation of the title in their documentation. 

[1]: https://github.com/jekyll/jekyll-seo-tag

**Comment by johnwmillr** [comment]
Has anybody come up with a solution for changing the tab titles? Judging from @misaleh's [site](https://mostafasaleh.com/) and the [example site](http://manifest.life) given by [@manifestlife](https://github.com/manifestlifeinc) in Issue #140, neither of them were able to change the tab titles.

I read the SEO tag documentation you linked, @mehmandarov but haven't been able to figure out a solution.
