### ISSUE TITLE
some icon doesn't rendered.

### ISSUE THREAD

**Issue by pegasusearl** [sergiokopplin/indigo#266]
excuse me, sorry if this might be a dumb report, but I really don't know why.
The twitter, facebook, and also linkedin icon doesn't get rendered.
<img src="https://cdn.pbrd.co/images/GTBXlrQ.png" />
https://pasteboard.co/GTBXlrQ.png

**Comment by mehmandarov** [comment]
It seems to be working fine here: http://koppl.in/indigo/. Can you provide output from the console when you run it locally? 

Can you also try cloning the repository again in a separate folder and following the instructions in the readme to run the jekyll server there to check if it works without any modifications?

**Comment by pegasusearl** [comment]
it actually screenshot from http://koppl.in/indigo/ EH-
So only me, hmm. I think i have experienced something like this in other theme before,..

Turns out that the problem was in my [adblocker](https://chrome.google.com/webstore/detail/bgnkhhnnamicmpeenaelnjfhikgbkllg), turned it off and everything is fine.
Thank you for your time, :D
