### ISSUE TITLE
Please help with following Issues 

### ISSUE THREAD

**Issue by sleebapaul** [sergiokopplin/indigo#282]
Issue 1: How to justify the paragraphs/images other than using the following workaround? 

```
<p style="text-align: justify">
Paragraph / Image
</p>
```
It's tedious that we need to do it for every paragraph separately.

Issue 2: How to save drafts of the posts? 

I tried to change the dates to future so that it won't be posted locally, but once GitHub builds it, all the posts are visible.

**Comment by thilak-rao** [comment]
@sleebapaul You can add your own CSS declaration to [helpers.sass](https://github.com/sergiokopplin/indigo/blob/gh-pages/_sass/base/helpers.sass) or any other sass file in your fork. 

Something like:

```sass
.justify
  text-align: justify
```

For drafts, just create a folder called `_drafts` in your project's root directory, and add markdown files like you would under `_posts`

**Comment by mehmandarov** [comment]
Thanks for suggesting a solution, @xthilakx. 👍 
On a (somehow) unrelated matter, @sleebapaul: [justify is bad for readability](https://designforhackers.com/blog/justify-text-html-css/). :-)

**Comment by sleebapaul** [comment]
It seems not working @xthilakx. I'm adding 
```{: style="text-align: justify;"}``` to each paragraph for the justification. 

@mehmandarov Point noted 😀
