### ISSUE TITLE
How to further increase the linewidth? (normal, large, veryLarge)

### ISSUE THREAD

**Issue by davidglavas** [sergiokopplin/indigo#284]
Every time I mess with the `width` value in the `config.yaml` file the linewidth on my page becomes huge and fills my whole screen. How can I gradually increase the line width?

**Comment by jehartzog** [comment]
The variable set there just adjusts the class assigned the the wrapper div [here](https://github.com/sergiokopplin/indigo/blob/dbf4f03ad8486c181542811ed21740671926f563/_layouts/default.html#L30).
```html
<div class="wrapper-{% if site.width == "normal" %}normal{% elsif site.width == "large" %}large{% endif %}">
```

You can then edit the sass [here](https://github.com/sergiokopplin/indigo/blob/dbf4f03ad8486c181542811ed21740671926f563/_sass/base/general.sass#L117).
```sass
.wrapper-normal
	max-width: 560px

.wrapper-large
	max-width: 810px
```
