### ISSUE TITLE
How to customize the favicon the right way?

### ISSUE THREAD

**Issue by davidglavas** [sergiokopplin/indigo#286]
There are over 15 favicon images (same image, different dimensions), what is the suggested way of replacing them with my own image? 

Do you use any shortcut to replace all of them without having to manually resize your image >15 times?

**Comment by mehmandarov** [comment]
You should be able to generate those with a favicon generator. Just search for one in your favourite search engine. 👍

**Comment by kunalbotla** [comment]
Can you specify one that works with this? And what settings if applicable.

**Comment by nlhomme** [comment]
> Can you specify one that works with this? And what settings if applicable.

[This one](https://favicomatic.com/) generates exactly what you need, with the same names.
Use the "Every damn size, sir!" option ;)
