### ISSUE TITLE
Post Advance Specification not working

### ISSUE THREAD

**Issue by noah978** [sergiokopplin/indigo#288]
I am trying to allow users to advance from one blog post to another, but not any projects. I have specified in my config.yml on the page advance item: [blog] but it doesn’t appear to be working properly. Here is my [page](/noah978/noah978.github.io/) Maybe i didn’t format it correctly.

Thanks

**Comment by mehmandarov** [comment]
I took a look at it now and it seem to be working fine for blog posts on your page now. In case you want to see the post-advance links also for projects you can do it like this: `post-advance-links: [blog, project]` in the _config.yml file. Closing this issue for now. Feel free to reopen if you encounter a bug in this functionality. Cheers!
