### ISSUE TITLE
Can i know that how to fix url

### ISSUE THREAD

**Issue by jhyejun** [sergiokopplin/indigo#289]
i want this

test.github.io/post-name (now) -> test.github.io/blog/post-name (want this)
test.github.io/project-name (now) -> test.github.io/projects/project-name (want this)

what should i do?

**Comment by spike1292** [comment]
To adjust the url's you have to edit the permalink here: https://github.com/sergiokopplin/indigo/blob/gh-pages/_config.yml#L22 to something like `/:categories/:title`.
Now you can use categories to identify different kind of posts. You can add category 'blog' or 'projects' 
in the front-matter section of you post, see https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts

**Comment by jhyejun** [comment]
Thank you for your help.
