### ISSUE TITLE
Spacing of nested lists in blogposts

### ISSUE THREAD

**Issue by davidglavas** [sergiokopplin/indigo#291]
I tried using nested lists in a blogpost and they look fine in GitHub's preview (when opening the .md file) but look different on the website. 

Is there a way to make the website's blogpost reflect the spacing in GitHub's preview?

GitHub's markdown preview:
![Github Markdown Preview](https://user-images.githubusercontent.com/18364494/38177634-bb1af150-3604-11e8-9b06-1957ae332b0b.png)

Blogpost:
![Website](https://user-images.githubusercontent.com/18364494/38177628-9ef82d76-3604-11e8-83d3-8796c4ce4cea.png)

**Comment by mehmandarov** [comment]
Unfortunately this is not possible at the moment, but you can always add your own CSS declaration to [helpers.sass](https://github.com/sergiokopplin/indigo/blob/gh-pages/_sass/base/helpers.sass) or any other sass file in your fork, as described here: https://github.com/sergiokopplin/indigo/issues/282.
