### ISSUE TITLE
Next and previous post links don't work for hidden posts

### ISSUE THREAD

**Issue by jehartzog** [sergiokopplin/indigo#292]
Since we use the [`page.previous`](https://github.com/sergiokopplin/indigo/blob/gh-pages/_layouts/post.html#L28) [variable](https://jekyllrb.com/docs/variables/), we have to special case and hide the links when they would link to a hidden post.

Ideally we would keep going in each direction until we find a post that is not hidden and link to that one, but is a more complicated fix than what we did in #278.

**Comment by sergiokopplin** [comment]
Do you need help on this @jehartzog? Still a problem?

**Comment by mehmandarov** [comment]
Your PR is now merged. Closing this issue. 
Also, see PR https://github.com/sergiokopplin/indigo/pull/346 that fixes another issue with that.
