### ISSUE TITLE
How to update my theme to the current version?

### ISSUE THREAD

**Issue by amirmasoudabdol** [sergiokopplin/indigo#303]
I'm using `indigo` as a theme for my website. I see that there have been several updates from the time that I've forked the template. I'm wondering what's the best way to update my theme while keeping my contents and tweaks? I've tried to `rebase` but I'm not sure if that's the best option. Is there any suggestion or known method in this situation?

**Comment by mehmandarov** [comment]
Hi, @amirmasoudabdol! You can for example make a local fork of Indigo theme and set your site with an upstream repo of that fork: So you have: `[your repo] --upsteam--> [local fork of Indigo] --upsteam--> [official Indigo]`. Then you can pull changes all the way down to your repo. In my opinion it is one of the more clean ways of doing this. 

Here is how you can keep your local fork up to date: https://help.github.com/articles/syncing-a-fork/.
