### ISSUE TITLE
Change to 2.2.5 to fix build error

### ISSUE THREAD

**Issue by drmenguin** [sergiokopplin/indigo#306]
https://github.com/sergiokopplin/indigo/blob/48675d87a6bd9e949fc892f2cbee00e8a709cefe/.travis.yml#L3

Changing this 2.2.5 _should_ fix the build error (it worked for my fork).

**Comment by mehmandarov** [comment]
Thanks, @drmenguin! I have done the changes and sent a PR: https://github.com/sergiokopplin/indigo/pull/307.

**Comment by mehmandarov** [comment]
Thanks, @drmenguin! I have made the changes and sent a PR: #307.
