### ISSUE TITLE
Adding custom javascript to blog posts

### ISSUE THREAD

**Issue by florianjosefreheis** [sergiokopplin/indigo#310]
I tried to add Chart.js to a blog post but Chart.min.js get not followed:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>`

Any ideas?

**Comment by florianjosefreheis** [comment]
Does anyone know how do add Chart.js to this template?

**Comment by sergiokopplin** [comment]
Hey @florianjosefreheis , sorry for the delay. Do you still need help?

**Comment by florianjosefreheis** [comment]
Hi @sergiokopplin, yeah, it would be great to see how I can add custom javascript to a blog post.
