### ISSUE TITLE
Indigo theme by Kopplin

### ISSUE THREAD

**Issue by jdzmfg** [sergiokopplin/indigo#313]
how can I get rid of this, I want to support the dev and I'm not trying to take credit for his code but it looks ugly on my website

**Comment by jehartzog** [comment]
You can easily find stuff like this on your own for the future, just type 'indigo theme' into the search bar at in github and it will show you the two places that shows up. Takes less than 10 seconds! 🥇 

I went ahead and [found it](https://github.com/sergiokopplin/indigo/blob/gh-pages/_includes/footer.html#L5) for you, edit that and you'll be good.
