### ISSUE TITLE
Can I Help with Translating This To GitLab?

### ISSUE THREAD

**Issue by TheCedarPrince** [sergiokopplin/indigo#314]
Hey team,

I was wondering if I could help with translating the Indigo theme to GitLab. I love the Jekyll theme and would like to move my personal fork over there.

I found [this]((https://gitlab.com/axil/sergiokopplin-indigo)) but was unable to get it to work in GitLab - moreover, the last build the user tried failed.

Can I help with anything and get this working? I would be happy to test and try things out.

Feel free to reach out to me here or through email. 

Yours,

~ TheCedarPrince

**Comment by antenore** [comment]
@TheCedarPrince I use indigo on gitlab without any problems on gitlab, I have just followed the gitlab pages tutorial

**Comment by TheCedarPrince** [comment]
Strange - @antenore, could you post your gitlab-ci.yml file? I am not sure where I am going wrong.

I can try again and see what happens. How did you bring Indigo over to GitLab? Did you change anything?

**Comment by antenore** [comment]
@TheCedarPrince my config is quite complex but basically I've used this sample https://gitlab.com/pages/jekyll/blob/master/.gitlab-ci.yml and worked around it

First be sure that the theme works nicely locally, than adapt the url in the config file.

**Comment by mehmandarov** [comment]
Seems like this is a platform specific question, and not connected to this theme. Closing issue.
