### ISSUE TITLE
New window fix & Open embed

### ISSUE THREAD

**Issue by luispuerto** [sergiokopplin/indigo#315]
Hi! 

First of all, thanks for your theme. It's really great. 

I'm having problems implementing this two solutions, which seem simple and I've been able to implement in other themes really easy: 

* [New window fix](https://jekyllcodex.org/without-plugin/new-window-fix/)
* [Open embed](https://jekyllcodex.org/without-plugin/open-embed/)

I've been able to implement [bigfoot](http://www.bigfootjs.com) footnotes in no time, just adding the [jQuery](https://jquery.com/download/) to the assets folder and calling the scripts in the head. 

However, I can make new window and open embed work... even if I call the jQuery specifically for them. Do you know what can I'm doing wrong? 

Thanks!

**Comment by sergiokopplin** [comment]
hey @luispuerto, do you still have this problem? We can help, let us know

**Comment by luispuerto** [comment]
sorry I no longer has this problem. The problem was the compression.
