### ISSUE TITLE
Recent gem updates break code/pre blocks in the theme

### ISSUE THREAD

**Issue by xuhaibahmad** [sergiokopplin/indigo#316]
I've been using this theme for quite some time now. However, after recent gem updates (cannot pinpoint which one exactly, should be kramdown or jekyll itself) I noticed code blocks appear to stretch right to the bottom of the page. 

Same can be seen on [your demo](https://koppl.in/indigo/markdown-common-elements/), notice how the first `pre` element never ends. It is more prominent when you have different background.

![image](https://user-images.githubusercontent.com/6507679/43699499-6b59e564-9968-11e8-8df7-bd703b5117f0.png)

Also, in the inspector view, the `code` block seems to never end and enclose all the proceeding tags inside.

![image](https://user-images.githubusercontent.com/6507679/43699524-8be7f9ce-9968-11e8-97c0-333703b0d794.png)

Here's a screenshot of my fork if it helps:

![image](https://user-images.githubusercontent.com/6507679/43699804-ab5d312e-9969-11e8-8c03-e8251743ddc8.png)

**Comment by busterswt** [comment]
This is also an issue for me. Local generation appears to work as expected.

**Comment by xuhaibahmad** [comment]
@busterswt Local will break too when you update the gems.

**Comment by busterswt** [comment]
@xuhaibahmad You're right, it did break. Since merging the upstream gh-pages branch into my fork and tweaking a few busted things, this problem as gone away locally and on GitHub pages. I forked over 1.5 yrs ago and never kept up.

**Comment by xuhaibahmad** [comment]
Turns out the issue is with Kramdown as suspected. Although there's no response on the [issue on kramdown repo](https://github.com/gettalong/kramdown/issues/536), I'm closing it here since it's irrelevant now.

**Comment by xuhaibahmad** [comment]
The Kramdown author doesn't acknowledge the problem and original issue got closed. Opening once again since I don't know where and what to look for. Hopefully, someone else will recognize this and help.

**Comment by xuhaibahmad** [comment]
.Updating to the latest versions of github-page (191) and kramdown (1.17.0) gems seems to have fixed the issue both locally and on gh-pages.
