### ISSUE TITLE
How to make the blog multi language?

### ISSUE THREAD

**Issue by FernandoFH** [sergiokopplin/indigo#317]
Hello everyone, 
This is less than a issues, it is more a request for help. I want to make the page have 2 languages ​​(Spanish / English) could you indicate how to do it (Some tutorial or something that gives me an idea), I'm new but I want to learn. 
Sorry if the query is very rookie. regards

**Comment by mhaeussermann** [comment]
Hey there,

I followed the approach by @ravpacheco to make my page multilingual. It basically involves a modification of the nav bar to add a language selector and the use of ref and lang tags. It's similar to the approach described in [this tutorial](https://www.sylvaindurand.org/making-jekyll-multilingual/), at least in principle. I don't have a tutorial for my/Rafael's approach at the moment, but I hope it becomes clear by looking at the code/commits.

Cheers

**Comment by mehmandarov** [comment]
Thanks for the reply, @FernandoFH! Closing this issue! 👍
