### ISSUE TITLE
Need to upgrade Ruby Sass

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#319]
This is the message I get when running `bundle update`. This means we should start looking into upgrading `Ruby Sass` package:

```
Post-install message from sass:

Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

**Comment by sergiokopplin** [comment]
I didn't get this message, do you still think this is a problem @mehmandarov?

**Comment by sylvainmetayer** [comment]
I still get this message when installing dependencies.

**Comment by mehmandarov** [comment]
@sergiokopplin ☝️

**Comment by mehmandarov** [comment]
Can you submit a PR, @sylvainmetayer?

**Comment by sylvainmetayer** [comment]
I don't have much time to look into it this week, but I'll try to make some progress on it next week

**Comment by sylvainmetayer** [comment]
Hi @mehmandarov @sergiokopplin ,

I didn't get time to look into this and sadly, won't have much time before 26th march. 

Does any of you found a solution ?

From what I've seen, we need to switch to [sassc](https://rubygems.org/gems/sassc) which seems to be the one elected to replace this library. 

Hopefully, their won't be any side effect.

**Comment by antenore** [comment]
My understanding is that the theme has nothing to change.
This is a Ruby deprecation of Sass which is transitioning to LibSass or Dart Sass.
Jekyll has a roadmap to swap out SAAS with their major version. 

I'd not worry about this.

cc: @sylvainmetayer @sergiokopplin

**Comment by sergiokopplin** [comment]
closing this then. we can improve all our dependencies in another branch/issue
