### ISSUE TITLE
Social links are missing on mobile Safari

### ISSUE THREAD

**Issue by kkarayannis** [sergiokopplin/indigo#326]
![untitled](https://user-images.githubusercontent.com/181362/48256429-d42a8980-e40f-11e8-9ae6-0d46c89687f3.png)

**Comment by sergiokopplin** [comment]
can you open a pr on this @kkarayannis?

**Comment by mehmandarov** [comment]
This seems to happen if you have a ad-block in Safari. Not able to reproduce on a latest Safari on iOS.

**Comment by mehmandarov** [comment]
@kkarayannis: This seems to happen if you have a specific 3rd party ad-block plugin installed in Safari. Not able to reproduce on a latest vanilla Safari on iOS. Please provide info on how to reproduce this issue during this week. I will close this issue if we don't hear from you by Feb 3rd. Cheers!

**Comment by kkarayannis** [comment]
Confirmed working using the latest mobile Safari with content blockers disabled. I’d swear I did check without content blockers when I opened the issue. Thanks anyway 👍

**Comment by mehmandarov** [comment]
That's all good, @kkarayannis. No worries. Happens to the best of us! It could also have been something that got fixed in a library we use or in Safari. Cheers!
