### ISSUE TITLE
Travis.sh is generated inside _site

### ISSUE THREAD

**Issue by sylvainmetayer** [sergiokopplin/indigo#327]
Is it possible to exclude some files when building _site ?

Steps to reproduce : 

- `bundle exec jekyll serve --config _config.yml,_config-dev.yml`
- Go to `http://localhost:4000/travis.sh`

Output : 
File is downloaded.

Expected : 404, because this file shouldn't be generated in `_site`

**Comment by mehmandarov** [comment]
Hi, @sylvainmetayer! Thanks for a detailed report. Yes, you can do this in _config.yml: https://jekyllrb.com/docs/configuration/options/. Would you like to fix this issue and submit a pull request?

Rustam

**Comment by sylvainmetayer** [comment]
Thanks for the link ! I'll look into it and submit a PR

**Comment by sylvainmetayer** [comment]
Sorry, bad commit reference. PR #328 is submitted :smiley:
