### ISSUE TITLE
Question : CSS inside HTML

### ISSUE THREAD

**Issue by sylvainmetayer** [sergiokopplin/indigo#334]
I'm asking myself why the CSS generated is not included inside a stylesheet. Is their a reason to do so, or should we move it to its own stylesheet ?

**Comment by sergiokopplin** [comment]
Hey @sylvainmetayer, performance purposes only. One of the google advices is the css inline

**Comment by sylvainmetayer** [comment]
I disagree with you. 

Google only recommend inline css when their is not much style (https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery#recommendations). 
When indexing *content*, google (or others search engine) don't really care about what your page look like, they care about content. So they probably (I'm not sure about this) won't load stylesheet and just HTML. If you put your css inside your HTML, they *have* to load it. Which result in a page that load slower, and maybe a slower rank. 

Beside, with HTTP2 becoming popular, loading the stylesheet in another file is the same, as the server can send a [push](https://www.nginx.com/blog/nginx-1-13-9-http2-server-push#configuring) command which will tells the browser to load the html page, and make a request to this file, because it know that it will need it. No need to make a first request, wait for answer, parse the file and then see that another file is required and sending another request !

It also allow external css files to be cached by the browser between different pages, which will make your site load faster.

The question is should we consider that this project has few style or not ? :smile:

**Comment by sergiokopplin** [comment]
I see.

![image](https://user-images.githubusercontent.com/2743180/51940215-8747c500-23f8-11e9-8692-46f26abce856.png)

Our score, today, mobile or desktop is 100%.
We can take a look if an update like this changes this result.
Indigo is from, like, 3/2 years ago. In that time it was a metric. So, i only could get 100% doing css inline.

In my opinion, this project has few styles and it is according to your sentence "Google only recommend inline css when their is not much style".

What you think?

**Comment by sylvainmetayer** [comment]
I agree that their is not much style for this project and if it allow to get 100/100, let's keep it this way !

**Comment by sergiokopplin** [comment]
Nice, but thanks for the question! It's Always important
