### ISSUE TITLE
No navigation links were shown unless posts had explicitly been set to not hidden

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#347]
After PR https://github.com/sergiokopplin/indigo/pull/278 no navigation links were shown unless posts had explicitly been specified as not hidden (`hidden: false`). PR https://github.com/sergiokopplin/indigo/pull/346 is meant to fix this issue by setting all posts to `hidden: false` by default. The setting can be overwritten in the front matter of a specific post that you might want to set to `hidden`.

**Comment by mehmandarov** [comment]
@sergiokopplin Ping. :)

**Comment by sergiokopplin** [comment]
278 merged!
