### ISSUE TITLE
Building site fails with `does not have a valid date in the YAML front matter` error

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#348]
Building site fails with `does not have a valid date in the YAML front matter` error.

```
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document
 'vendor/bundle/ruby/2.4.0/gems/jekyll-3.7.3/lib/site_template/_posts/0000-00-00-welcome
-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

**Comment by mehmandarov** [comment]
@sergiokopplin Ping. :)

**Comment by eric-tramel** [comment]
@mehmandarov I'm running into the same issue with a fresh (as of today) install of Ruby & Jekyll.

**Comment by mehmandarov** [comment]
@eric-tramel: There is a pull request waiting to be merged to fix this issue: https://github.com/sergiokopplin/indigo/pull/349.

**Comment by pierre10101** [comment]
In the meantime I fixed this by excluding the path folder in my _config.yml file.  I am using rbenv and do not have a vendor folder.

**Comment by sergiokopplin** [comment]
It seems to not be happening anymore. Can you guys check that too? No errors here. Closing for now
