### ISSUE TITLE
All links are shown with the site's image, instead of the image specified in the `image` field in the post's front matter

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#350]
Unfortunately, I think we need to revert PR https://github.com/sergiokopplin/indigo/pull/341. The result of this change is that all links will be shown with the site's image, instead of the image specified in the `image` field in the post's front matter. This is unfortunate, as the latter will always be ignored.

**Comment by danilogila** [comment]
Any news about this?

**Comment by mehmandarov** [comment]
Thanks for pinging! Waiting for @sergiokopplin to approve this PR. I don't want to push code without peer-review. I have been running it on my site for quite some time without any issues.

**Comment by mehmandarov** [comment]
@sergiokopplin Ping. :)

**Comment by sergiokopplin** [comment]
merged
