### ISSUE TITLE
Social icons are not being rendered on the new Chrome versions

### ISSUE THREAD

**Issue by skhaz** [sergiokopplin/indigo#355]
Hi,

I noticed that all social icons are not being rendered on the Chrome (in Firefox are okay). Any clues?

<img width="766" alt="screen shot 2019-02-19 at 11 53 23" src="https://user-images.githubusercontent.com/46259/53023987-fbe0b300-343c-11e9-8de8-b076d054243e.png">

**Comment by mehmandarov** [comment]
Can you check your ad-blocker? Some of them are too aggressive and block those images as well.

**Comment by skhaz** [comment]
Thanks @mehmandarov, was the ad-blocker
