### ISSUE TITLE
GitHub pages breaks github social link

### ISSUE THREAD

**Issue by Twister915** [sergiokopplin/indigo#358]
The value of `{{ site.github }}` evaluates to an object (presumably provided, automatically, by Github pages) and causes the GitHub social link to always lead to `http://github.com/{`

The object we got looks like [this](https://gist.github.com/Twister915/afaabca8b855709e8b2480218937d893)

This could perhaps be fixed by changing the name of the key `github` to `github_link`?

**Comment by mehmandarov** [comment]
Do you have the "github" key set to anything in your _config.yml file? It should be `github: yourgithubusername`.

**Comment by mehmandarov** [comment]
Closing this issue for now. Feel free to reopen if you believe this is a bug.
