### ISSUE TITLE
how to setup Disqus in my blog and post

### ISSUE THREAD

**Issue by iamrajiv** [sergiokopplin/indigo#360]
I hade searched about how to set up Disqus is my blog and post and I found that we have to go to `_layouts` and inside it, we have to edit `post.html` but what I have to add and where I have to add.

**Comment by mehmandarov** [comment]
Hi, @iamrajiv! Have you tried setting up the `disqus` section in `_config.yaml`. Remember to set up the `categories` field there, e.g. blog, project, etc.

**Comment by mehmandarov** [comment]
Feel free to reopen this issue if this does not help.

**Comment by iamrajiv** [comment]
@mehmandarov thank you, sir, for guidance 
in my `_config.yaml` and in `categories` blog, project are already added

![1](https://user-images.githubusercontent.com/42106787/55199492-32e67900-51e0-11e9-9a8a-6c047d194970.PNG)

But still it is not loading

![2](https://user-images.githubusercontent.com/42106787/55199544-5c070980-51e0-11e9-8281-d3dea25c6e49.PNG)

**Comment by iamrajiv** [comment]
@mehmandarov do I have to add any link or text in `blog` of `index.html` or any other file
