### ISSUE TITLE
Posts was deleted after build

### ISSUE THREAD

**Issue by ln0rd** [sergiokopplin/indigo#364]
after i to create a post and done build my post is deleted.

**Comment by mhaeussermann** [comment]
Hi LeonardoLB,
if you mean the post "2019-04-27-Aprendizado-e-frustracao.md" in your _posts folder: the most likely reason for your issue is that the post's publication date is **April** 27, 2019. Just change the date to March and the post should appear.  Hope this helps!

**Comment by ln0rd** [comment]
i'm thankful for your help, i found what i was wrong, inside the file _config.yml need set to property `future: true` to accept new posts. and i put the wrong month haha thank you

**Comment by mehmandarov** [comment]
Great you got this figured out. Closing the issue. 👍
