### ISSUE TITLE
Social links icons are not visible

### ISSUE THREAD

**Issue by igibek** [sergiokopplin/indigo#374]
The social networks icons are not visible in the browser. I can see them using view source code. However, they are not visible on the main page.

**Comment by igibek** [comment]
Even on the demo page, the social links are not visible on Chrome. You can see HTML code for social links using developers tool, but they are not visible. 
On safari, social links are displayed properly.

**Comment by mehmandarov** [comment]
Could it be because of ad-blocking plugin, @igibek?

**Comment by sergiokopplin** [comment]
Closing, it seems ok here
