### ISSUE TITLE
Black theme

### ISSUE THREAD

**Issue by Rush-er** [sergiokopplin/indigo#375]
im new to this.. there is a fast way to get the site black themed like this ?
![Image](https://i.imgur.com/I1lE62b.png)

I looked at [this](https://aqeel.cc/2018/09/25/dark-reader-theme-on-your-website/) but the layout is not correct

**Comment by mwt** [comment]
Editing the colors in /_sass/base/variables.sass should get you most of the way there.

**Comment by Rush-er** [comment]
Tested, i can change the string color etc. but no the background, thanks btw

**Comment by mhaeussermann** [comment]
Just add a line to "body" in general.sass with "background-color: $VARIABLE" and you should be fine.

**Comment by Rush-er** [comment]
> Just add a line to "body" in general.sass with "background-color: $VARIABLE" and you should be fine.

ok it works, thanks

**Comment by sergiokopplin** [comment]
Nice work @Rush-er @mhaeussermann @MattWThomas! It looks awesome
