### ISSUE TITLE
google speed

### ISSUE THREAD

**Issue by sergiokopplin** [sergiokopplin/indigo#38]
85 / 100 for User Experience
how can i fix this?

**Comment by rootulp** [comment]
Can you post your results from Google PageSpeed Insights?
I'm getting [96/100](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Frootulp.com%2F&tab=mobile) for User Experience for rootulp.com

**Comment by sergiokopplin** [comment]
take a look: https://developers.google.com/speed/pagespeed/insights/?url=koppl.in%2Findigo
i'm going to update the styles for the buttons (social links) and i hope that solves the problem

**Comment by sergiokopplin** [comment]
[done](https://github.com/sergiokopplin/indigo/commit/a9f05bdc6e352f6e9ddcb5e0a2b365036deb7856)!
the problem was the small buttons. now they have a new size
