### ISSUE TITLE
Only bake icons to html if they are being used

### ISSUE THREAD

**Issue by mwt** [sergiokopplin/indigo#382]
I've opened up a simple pull request for this minor optimization #381

It just makes the HTML file *slightly* smaller. It's particularly nice if anyone wants to add more icons in the future.

I conditioned the insertion of the inline SVGs on the variables in the main config file.

**Comment by sergiokopplin** [comment]
Someone else made a thing that fixed this! But it was merged. Thanks @MattWThomas
