### ISSUE TITLE
make a collapsible menu for the header for mobile

### ISSUE THREAD

**Issue by iamrajiv** [sergiokopplin/indigo#385]
In mobile, I see the header menu expanded vertically.

![Capture](https://user-images.githubusercontent.com/42106787/59940492-7287ce80-9478-11e9-8bba-4d08c4a87dce.JPG)

This doesn't look good to me. I think it'd be better a collapsible menu.

**Comment by sergiokopplin** [comment]
Can you open a pull request with that feature? 🤓
