### ISSUE TITLE
Language of mydisqus

### ISSUE THREAD

**Issue by subaiwen** [sergiokopplin/indigo#388]
The language of comment/discussion area is Korean. How can i convert it to English. Thanks

**Comment by underdogliu** [comment]
Got the same problem as well. Tried to search for `kr` but seems nothing relevant popped up. Anybody got solutions of hints?

**Comment by underdogliu** [comment]
@subaiwen So not sure if you have solved the problem but I kinda figured it out (and also, for other people that encountered this problem as well).

A simple solution is you may want to register [Disqus](https://disqus.com/home/) and follow the instructions [here](https://desiredpersona.com/disqus-comments-jekyll/) to create your 'pool'. Then (after waiting for a while maybe?) you can change the `shortname` tab of `disqus` section in `config.yml` to activate your Disqus in your posts.

Hope it helps.

**Comment by subaiwen** [comment]
@underdogliu Thanks. I activated my shortname before reporting this issue. The problem was that the `disqus` section was in Korean. I disabled the section by commenting it out. 
I tried the instruction you provided. The `disqus` section is gone, even though I enable it in `config.yml`

**Comment by underdogliu** [comment]
@subaiwen hmm....it worked for me :thinking: 

and just went to one of your blogs, it looks like you are having a english ver. of disqus enabled

**Comment by subaiwen** [comment]
@underdogliu Sorry, I forgot to reply. I got the error email from GitHub said ```You have an error on line 1 of your `_config.yml` file```. So I revised the `_config.yml` file and It worked! The essential part was to get a short name, register the website, and change the language in `disqus`. Thanks again.
