### ISSUE TITLE
Migrate to jekyll-paginate-v2

### ISSUE THREAD

**Issue by heychirag** [sergiokopplin/indigo#393]
Since jekyll-paginate is no longer under active development and maintenance, we should migrate to jekyll-paginate-v2 in the near future. It is also more feature-rich than the previous version.

**Comment by mehmandarov** [comment]
Hi, @heychirag! Good idea! Could you look into that and submit a PR?

**Comment by heychirag** [comment]
@mehmandarov, check #395.

**Comment by mehmandarov** [comment]
The PR https://github.com/sergiokopplin/indigo/pull/395 has now been merged. Closing the issue. Thanks, @heychirag!
