### ISSUE TITLE
using jekyll-archives to generate tag pages

### ISSUE THREAD

**Issue by heychirag** [sergiokopplin/indigo#394]
I recently integrated jekyll-archives into my blog. This helped me replace the default tags page with something that has a separate page for each tag. I think this could be better for SEO and especially for bigger blogs. Further, I also used it to display posts year wise.

Have a look at my blog https://chia.ro and the screenshots below. If I get positive reviews, I could submit a PR.

![Screenshot 2019-08-18 at 2 59 47 PM](https://user-images.githubusercontent.com/13611666/63222718-eae4e480-c1c8-11e9-9f05-85a1cfa77620.png)
![Screenshot 2019-08-18 at 2 59 22 PM](https://user-images.githubusercontent.com/13611666/63222719-eae4e480-c1c8-11e9-837a-2be5f205cc22.png)

**Comment by sergiokopplin** [comment]
Hey @heychirag. It seems great! Can you help us with a pull request? Thanks

**Comment by heychirag** [comment]
@sergiokopplin do you want me to submit a PR for this?

**Comment by sergiokopplin** [comment]
Yeah, you can do that! Make sure that you can turn this off anytime inside config files. It seems to be a good feature for everybody,
