### ISSUE TITLE
After configuring as explained, Site not found

### ISSUE THREAD

**Issue by alrevuelta** [sergiokopplin/indigo#396]
I have forked the repo and modified the `_config.yml` file with my `http://USERNAME.github.io` url, but when I type it in the browser,  I get "404 Site not found". I have even tried changing the repo name to `username.github.io` but still no luck. Am I the only one facing this issue? Its not the first time I set up a github pages theme, but I can't get this one to work.

Thanks!

**Comment by heychirag** [comment]
It's probably an issue with Github itself, not this theme. I am using this with Gitlab and it is working totally fine with it.

**Comment by alrevuelta** [comment]
Nice to know it is working in Gitlab. Have you tried with GitHub?

**Comment by heychirag** [comment]
Nope.

**Comment by sergiokopplin** [comment]
Have you tried with https? The docs are fine. Can you put a step by step of what you did?

**Comment by alrevuelta** [comment]
Still not working for me. I even created a new GitHub account and tried, but no luck, even with https as you suggested. This is what I have done:
* Fork the project
* Change the repo name to "myUserName.github.io"
* Edit `_config.yml` with https://myUserName.github.io

Thanks!

**Comment by sergiokopplin** [comment]
I've checked your pull request and it seems all fine. Have you tried moving your branch from gh-pages to master? Then you can go to settings and check if everything is fine.

**Comment by sergiokopplin** [comment]
Let's close the issue and solve your problem with this closed.

**Comment by alrevuelta** [comment]
Solved! That was the issue, I had `gh-pages` as default, don't know why though, changing it to `master` fixes the issue. Thanks!
