### ISSUE TITLE
failed in bundle install

### ISSUE THREAD

**Issue by ghost** [sergiokopplin/indigo#408]
after I type in bundle install, I get this massage:

Fetching gem metadata from http://rubygems.org/...........
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies....
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.13.0
Using thread_safe 0.3.6
Using tzinfo 1.2.6
Using activesupport 5.2.4.1
Using public_suffix 3.1.1
Using addressable 2.7.0
Using backports 3.15.0
Using bundler 2.1.2
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using coffee-script 2.4.1
Using colorator 1.1.0
Using ruby-enum 0.7.2
Fetching commonmarker 0.17.13
Installing commonmarker 0.17.13 with native extensions
Errno::EACCES: Permission denied @ dir_s_mkdir -
/Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/commonmarker-0.17.13
An error occurred while installing commonmarker (0.17.13), and
Bundler cannot continue.
Make sure that `gem install commonmarker -v '0.17.13' --source
'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 203, which depends on
    jekyll-commonmark-ghpages was resolved to 0.1.6, which depends on
      jekyll-commonmark was resolved to 1.3.1, which depends on
        commonmarker

**Comment by sergiokopplin** [comment]
this is a deleted account, closing this
