### ISSUE TITLE
Emoji on bio

### ISSUE THREAD

**Issue by ganjarpanji** [sergiokopplin/indigo#410]
Is it possible to add emoji on bio?

**Comment by ganjarpanji** [comment]
i tried using :rain_cloud:  but its not displayed

**Comment by sergiokopplin** [comment]
It's possible, my test was -> A Man who travels the world eating noodles 🚀

![image](https://user-images.githubusercontent.com/2743180/72273035-6330c400-3608-11ea-8d87-3d65c5a31739.png)

**Comment by ganjarpanji** [comment]
somehow it only works for rocket emoji LOL
