### ISSUE TITLE
is there a way to embed GIF in the posts?

### ISSUE THREAD

**Issue by amansingh9097** [sergiokopplin/indigo#417]
So far I have tried embedding the GIFs in the markdown as,
```
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
```
but it seems this never works on this theme. So is there a better way to embed GIF in the markdown post files?

**Comment by sergiokopplin** [comment]
Have you tried this one? https://github.com/vfalanis/jekyll-giphy

**Comment by amansingh9097** [comment]
But that would be able to add only the giphy GIFs. How to add my own GIFs?

**Comment by sergiokopplin** [comment]
https://stackoverflow.com/questions/34341808/is-there-a-way-to-add-a-gif-to-a-markdown-file

Does this help you?

**Comment by sergiokopplin** [comment]
We need to check that then. Help needed.

**Comment by sergiokopplin** [comment]
Does this help you @amansingh9097 -> https://brettterpstra.com/2015/08/20/a-jekyll-plugin-for-animated-gifs/

**Comment by sergiokopplin** [comment]
Let me know

**Comment by imyilin** [comment]
yes




------------------原始邮件------------------
发件人： &nbsp;“ SérgioA . Kopplin” <notifications@github.com&gt;;
发送时间： &nbsp;2020年2月29日（星期六）凌晨0:41
收件人： &nbsp;“ sergiokopplin / indigo” <indigo@noreply.github.com&gt;;
抄送： &nbsp;“ Subscribed” <subscribed@noreply.github.com&gt;;
主题： &nbsp;回复：[sergiokopplin / indigo]是否可以在帖子中嵌入GIF？（＃417）




封闭式＃417。
  
— 
您收到此消息是因为您已订阅该线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by amansingh9097** [comment]
Hi @sergiokopplin 

I'm sorry I'm new to jekyll themes, can you help me with, how I can add that jekyll plugin to your theme so that I can showcase some GIFs in my posts? Thanks
