### ISSUE TITLE
Icons are bigger than they should be

### ISSUE THREAD

**Issue by kunalbotla** [sergiokopplin/indigo#419]
The icons on the pages seem bigger than they should be. This is running locally with a clean download. Please look at the attached screenshot so you can see exactly what I mean.

<img width="1266" alt="Screen Shot 2020-02-07 at 9 41 26 AM" src="https://user-images.githubusercontent.com/25641153/74038402-20a3a280-498e-11ea-8dba-3b76e42cc011.png">

**Comment by sergiokopplin** [comment]
We've fixed that no a PR. Is your branch updated?

**Comment by kunalbotla** [comment]
I think it is. I cloned it just 6 hours ago... Do I use a pull request to update it?

**Comment by kunalbotla** [comment]
It looks to be the latest branch.

**Comment by jayloofah** [comment]
I have the same issue as well, the icons referenced from the new source appear are much larger and the height/width parameters that size the icons have increased it seems.

The footer icons and rss icons have increased to 25px and 40px respectively.

**Comment by jayloofah** [comment]
Also curious if all of these changes made recently will be pushed into a new release or will update the static page demo?

**Comment by sergiokopplin** [comment]
I've merged a PR. can you guys check if it works?

**Comment by kunalbotla** [comment]
I just got to check this and it looks like the issue if fixed.
