### ISSUE TITLE
Support for google-scholar and orcid icons

### ISSUE THREAD

**Issue by MayankKr8** [sergiokopplin/indigo#423]
The theme covers all necessary icons for social media/networks. However, lacks support for research networks such as google-scholar and Orcid. Can someone please look into it?

**Comment by sergiokopplin** [comment]
Hey @MayankKr8. I think the best you for you to do that is importing an Icon that you want to render.
If you find any Jekyll package that does that, we can implement, otherwise it seems to be a very specific use case.
