### ISSUE TITLE
On mouse-hover the title of the "fas.fa-*" icons overlaps the content

### ISSUE THREAD

**Issue by gforghieri** [sergiokopplin/indigo#427]
**The below pictures tell it all.** That title is generated and injected somehow into the HTML.
Can we get rid of them please? This is extremely annoying, from a user-experience perspective.

@sergiokopplin, @sylvainmetayer 

![Untitled](https://user-images.githubusercontent.com/23422651/76472145-fca40880-63f4-11ea-9997-26a4b59c99b8.png)

![old_untitled](https://user-images.githubusercontent.com/23422651/76472155-00d02600-63f5-11ea-91df-5313e2a26b93.png)

**Comment by sylvainmetayer** [comment]
Hello, this is indeed an annoying error. 

Removing the title in the svg definition should fix this, but I'm wondering if from an accessibility point of view, this would be a good choice ?

**Comment by sergiokopplin** [comment]
Have you tried that solution @gforghieri?

**Comment by sergiokopplin** [comment]
I've made [these](https://github.com/sergiokopplin/indigo/pull/483/files) changes.
So, I've removed all things related with that hover behavior.
