### ISSUE TITLE
Posts not showing on list

### ISSUE THREAD

**Issue by kunalbotla** [sergiokopplin/indigo#428]
My posts are not showing up on the list. I am able to create posts, but they just don't show up. I've even tried just duplicating the posts already made and changing their name to see if that works.

**Comment by mehmandarov** [comment]
Hi, @kunalbotla! Do you have an example of such posts you can link to here?

**Comment by kunalbotla** [comment]
They are on my repo at https://github.com/kunalbotla/indigo

**Comment by kunalbotla** [comment]
@mehmandarov I'm not able to publish it right now because I am waiting for the GitHub Pages issue to be resolved.

**Comment by mehmandarov** [comment]
You can still test it locally. Also with a [Docker image](https://mehmandarov.com/disposable-docker-containers/). Can you try removing `externalLink: false` in the fornt matter (i.e. header in the post)? This should resolve your issue.

**Comment by kunalbotla** [comment]
@mehmandarov: I am currently testing it locally. I just tried removing that but it does not seem to solve the issue.

**Comment by mehmandarov** [comment]
Can you also check that you have a correct category? If should be `category: blog`.

**Comment by kunalbotla** [comment]
@mehmandarov, I want it to show up in projects so I set it to `category: project`

**Comment by kunalbotla** [comment]
@mehmandarov it should show up in the list automatically correct?

**Comment by mehmandarov** [comment]
Could you please provide us with steps to reproduce the issue, with information about what are you doing, what are the expected results and what are you getting instead, as well as some code examples. It will be much easier to help you then. :)

**Comment by sylvainmetayer** [comment]
You should not edit the category but add the `projects` to `true` in the front matter of your post. See [here](https://raw.githubusercontent.com/sergiokopplin/indigo/master/_posts/2016-01-23-indigo-jekyll-theme.markdown) for an example

**Comment by kunalbotla** [comment]
It just started working again after I cloned it again.
