### ISSUE TITLE
Why is Disqus like this?

### ISSUE THREAD

**Issue by kunalbotla** [sergiokopplin/indigo#438]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/25641153/79678303-e5acbf00-81c7-11ea-9a44-81c6eaf67645.png">

**Comment by sergiokopplin** [comment]
Have you fixed @kunalbotla? Where that was happening?

**Comment by kunalbotla** [comment]
Yes, I just had an issue with my Disqus settings, it was on their end.
