### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by heychirag** [sergiokopplin/indigo#439]
Support for dark theme as this is the new fad.

**Comment by sergiokopplin** [comment]
I've done some changes in a branch locally, but it needs some refactor. I'll push it later, then we can work together on that

**Comment by Nazeeefa** [comment]
Thanks @sergiokopplin! Option to switch from light to dark theme would be great and useful!

**Comment by notSeaSmoke** [comment]
Any updates on this?

**Comment by sergiokopplin** [comment]
Hey Guys!
I was thinking about it.
Have you guys tried the Dark Read for Chrome? It seems a good theme colour to apply in a dark mode.

**Comment by Nazeeefa** [comment]
Do you mean the Chrome extension https://darkreader.org/ ? :) Yes, it has a nice dark colour.
It would be nicer to have button in indigo theme that allows to switch between dark and light.

**Comment by notSeaSmoke** [comment]
Having a native dark mode integration on the site itself is better than using an extension, especially considering that most mobile browsers don't have extension support.

**Comment by sergiokopplin** [comment]
@notSeaSmoke Agree! My idea it to have just an inspiration on colors to apply here, not to use the extension itself.

**Comment by notSeaSmoke** [comment]
Oh yeah, that makes more sense. Personally, I find the Dark Reader theme a bit _too_ dark. I prefer a color scheme like GitHub's new Dark Dimmed theme, it's dark enough to not cause eye strain while also being light enough to not cause reading issues like pure black themes. The dynamic theme engine in Dark Reader with default settings is the closest to what I'd personally like.

**Comment by sergiokopplin** [comment]
What do you guys think about? https://github.com/sergiokopplin/indigo/pull/484

**Comment by sergiokopplin** [comment]
@heychirag @Nazeeefa @notSeaSmoke I've made a proposal.

**Comment by sergiokopplin** [comment]
I'll merge, 🐛 are expected hahaha

**Comment by sergiokopplin** [comment]
demo: https://koppl.in/

**Comment by Nazeeefa** [comment]
Thanks. Dark theme looks nice, what sort of bugs should we expect?
I guess, it's not possible to have dark/bright mode button?

**Comment by sergiokopplin** [comment]
@Nazeeefa yeah, it's possible, but it will add some javascript. We don't have any js 
Do you know any other ways of doing @Nazeeefa ?

**Comment by vidhatha** [comment]
@sergiokopplin any plans to add the button using js?
