### ISSUE TITLE
pagination doesn't work with github pages

### ISSUE THREAD

**Issue by bodenr** [sergiokopplin/indigo#444]
It appears pagination doesn't work when using this theme with github pages.

I initially had pagination enabled and when testing my blog locally things were working as expected; when viewing my blog on `localhost:4000/blog` my posts where showing up as desired. However, when I pushed my site to github and viewed the resulting github.io page for my blog, the string `page of` was showing rather than my list of blog posts. The github build of this site was not reporting any errors (under the `Settings` for the repo).

To mitigate I disabled pagination in my `_config.yml` and also commented out the `gem "jekyll-paginate-v2", "~> 2.0"` in my Gemfile. After pushing with pagination disabled, I now see my posts on my github.io blog page.

I'm no rubyist, but I'm wondering if this theme's dependency on `jekyll-paginate-v2` could be the issue? Based on github pages dependency versions (https://pages.github.com/versions/) I see they use `jekyll-paginate 1.1.0` whereas this theme uses `"jekyll-paginate-v2", "~> 2.0"`.

I don't have a requirement to use pagination so I'm fine running without, but wanted to report this issue in case it's something that the author(s) want to address.

**Comment by sergiokopplin** [comment]
Hey @bodenr 
Have you fixed it?

It's a bit old, so I'm closing, but any new or persistence bugs, send for us here
