### ISSUE TITLE
url doesn't map correctly?

### ISSUE THREAD

**Issue by CunningLearner** [sergiokopplin/indigo#448]
I just tried forking this around and rename repo to `USERNAME.github.io` and change url to: `USERNAME/github.io` in _config.yml
It says site not found at USERNAME.github.io

Though, i tried with `something` as repo  `USERNAME.github.io/something` as url in _config.yml and it works well.
Whats the problem without /something? I want my home landing at USERNAME.github.io

**Comment by iamgmujtaba** [comment]
I have same problem. 
Did you solve it @CunningLearner ?

Thanks in advance

**Comment by CunningLearner** [comment]
> I have same problem.
> Did you solve it @CunningLearner ?
> 
> Thanks in advance

Not yet!
I am still on `/something` which I didn't like at all.

**Comment by sergiokopplin** [comment]
Hey guys! Have you fixed? Sorry for the delay
