### ISSUE TITLE
Renaming tabs or adding new ones. 

### ISSUE THREAD

**Issue by DariushNejad** [sergiokopplin/indigo#450]
I'm not that experienced with coding or writing scripts. I wanted to know if anyone could tell my how to rename the Resume tab? Or perhaps how I can add new tabs?

**Comment by CasLudwig** [comment]
I wondered exactly the same. Love this theme, but would like to be able to rename resume and perhaps add one more tab...

**Comment by sergiokopplin** [comment]
You can rename the tabs here -> _includes/nav.html

But adding more tabs, dynamically, is not possible :(
