### ISSUE TITLE
Add fediverse (ie. Mastodon) social link

### ISSUE THREAD

**Issue by Niquarl** [sergiokopplin/indigo#458]
I'd like to be able to add some fediverse social links on top of the usual twitter, github, email etc. So basically Mastodon, Pixelfed, PeerTube and the like
If I understand correctly I need to add each social media as all the others in config.yml but then I'm not sure how to do the rest. I think I need to add each website in the _includes/social-links and _includes/icons
For the social-links I think I understand how to do that just copying the same format the rest and changing the need links etc.
But for the icons I don't know what this is supposed to be:
` <path
                class="path1"
                d="M122.88 122.88v121.19c362.803 0 656.896 294.195 656.896 656.998h121.293c0-429.773-348.416-778.189-778.189-778.189zM122.88 365.414v121.293c228.813 0 414.362 185.498 414.362 414.413h121.242c0-295.834-239.821-535.706-535.603-535.706zM239.053 668.621c-64.205 0-116.224 52.122-116.224 116.275s52.019 116.224 116.224 116.224 116.173-52.019 116.173-116.224-51.968-116.275-116.173-116.275z"
            ></path>`

More explicitely what the `d="???"` is supposed to refer to. Are all those numbers linking to an image in the files or something external ?

**Comment by Niquarl** [comment]
Ok, fixed the icon. Would still be cool to have fediverse social stuff in the basic.

**Comment by mwt** [comment]
For anyone else that wants to do this, the following icon works:
```
<symbol id="icon-mastodon" viewBox="0 0 1024 1024">
<path class="path1" d="M872.1 592.2c-11 57-99 119.2-200 131.3-52.8 6.2-104.6 12-160 9.5-90.4-4.2-161.8-21.6-161.8-21.6 0 8.8.5 17.2 1.6 25 11.8 89.3 88.5 94.7 161.3 97.2a465.6 465.6 0 00138.7-18.1l3 66.3s-51.3 27.6-142.8 32.7c-50.4 2.7-113-1.3-186-20.6C168 852 140.8 683.4 136.6 512.3c-1.3-50.8-.5-98.7-.5-138.8 0-175 114.6-226.2 114.6-226.2 57.8-26.5 157-37.7 260.1-38.5h2.5c103.1.8 202.4 12 260.2 38.5 0 0 114.6 51.3 114.6 226.2 0 0 1.4 129.1-16 218.7zM753 387.2c0-43.4-11-77.8-33.2-103.2-22.8-25.5-52.7-38.5-89.8-38.5-43 0-75.5 16.5-97 49.5L512 330l-20.9-35c-21.5-33-54-49.5-97-49.5-37.1 0-67 13-89.8 38.5C282 309.4 271 343.8 271 387V599h84V393.3c0-43.3 18.2-65.3 54.6-65.3 40.4 0 60.6 26 60.6 77.7v112.5h83.4V405.7c0-51.6 20.2-77.7 60.6-77.7 36.4 0 54.7 22 54.7 65.3V599h83.9V387.1z"></path>
</symbol>
```

You can implement support by copying the changes in [this commit](https://github.com/mwt/mwt.github.io/commit/9ef3fc9676fdfde7ebbf780c9cd40f4f0917d9c0). I'm happy to submit a pull if there is sufficient interest in this.
