### ISSUE TITLE
Add support for Google Scholar in socials

### ISSUE THREAD

**Issue by kartik144** [sergiokopplin/indigo#459]
Hi,

Would it be possible to add support for google scholar icon in socials?

Icon Image PNG: https://www.cleanpng.com/png-google-scholar-education-research-doctor-of-philos-1739102/

**Comment by TomNissens** [comment]
All icons for academia: http://jpswalsh.github.io/academicons/

**Comment by mwt** [comment]
I have this implemented in my fork:
https://github.com/mwt/mwt.github.io/

The icon itself is
```
<symbol id="icon-gscholar" viewBox="0 0 1024 1024">
<title>gscholar</title>
<path class="path1" d="M1002 382v405H889l1-336-394 212L22 382 496 70l506 312zM216 619v168l281 168 279-168V619L496 787 216 619z"/>
</symbol>
```

You can see it live [here](https://mattwthomas.com). If there's enough interest, I'm happy to make a pull request.
