### ISSUE TITLE
can disqus show in English?

### ISSUE THREAD

**Issue by josephchenhk** [sergiokopplin/indigo#461]
Hi all, my question might sounds silly. But I can't find the place to change the language config in disqus. And my disqus panel shows something in Korean. Any ideas to solve it? Many thanks!

<img width="903" alt="Screenshot 2020-07-24 15 37 32" src="https://user-images.githubusercontent.com/2732840/88370197-25d19e00-cdc4-11ea-9b70-82bfd8a1764d.png">

**Comment by lishichengyan** [comment]
You need to register a disqus account and replace the shortname of your own in _config.yml. Hope this helps!

**Comment by josephchenhk** [comment]
Thanks dude! I got it work now! Just in case other people also have similar issues, here is the additional tip: after replacing the shortname in _config.yml, you also need to put your domain to trusted domains in disqus: https://help.disqus.com/en/articles/1717301-i-m-receiving-the-message-we-were-unable-to-load-disqus

Allow me to close this issue now. Thanks again!
