### ISSUE TITLE
Could not fetch the Config! (Admin panel) 

### ISSUE THREAD

**Issue by LinX64** [sergiokopplin/indigo#487]
There's an error after opening the admin panel. It says: "Could not fetch the Config"

Any suggestions/ideas?

**Comment by sergiokopplin** [comment]
Hey @LinX64, it seems a bug from jekyll admin. But I'm really not sure about it.
I've searched but found nothing.

But the admin page itself seems to be working properly.

Are you having trouble with the admin panel?
