### ISSUE TITLE
I get the following issue when trying to 'bundle exec jekyll serve' : 

### ISSUE THREAD

**Issue by javisth** [sergiokopplin/indigo#488]
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'

**Comment by sergiokopplin** [comment]
Fixed! It was related to jekyll-admin.
