### ISSUE TITLE
Posts are not visible

### ISSUE THREAD

**Issue by thedevmanek** [sergiokopplin/indigo#492]
I have created posts but they are not visible. 
https://thedevmanek.github.io
and link to post 
https://github.com/thedevmanek/thedevmanek.github.io/tree/master/_posts

**Comment by mehmandarov** [comment]
It seems to be visible now. Did you fix the issue?

**Comment by thedevmanek** [comment]
I'm using Chalk now I've changed the template. The issue exists in my local setup

**Comment by smiile8888** [comment]
Seems like I got the similar problem. Posts are not visible when published on the Github page. It works fine on local, though.
For reference: https://thesmile.me/blog/ and https://github.com/smiile8888/blog/tree/gh-pages/_posts

**Comment by sergiokopplin** [comment]
@smiile8888 have you tried to change this line? https://github.com/smiile8888/blog/blob/gh-pages/_config.yml#L79
