### ISSUE TITLE
Discussion on possible contributions

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [sergiokopplin/indigo#498]
Hello @sergiokopplin ,

I have been working on some features in my fork that you might want upstream, such as accent colors, and custom backgrounds. I do not know if you want these changes in your code, perhaps because they mix configurations with programming.

You can see my website here https://ricardoeprodrigues.github.io/

And here is the commit that added the accent colors: https://github.com/RicardoEPRodrigues/ricardoeprodrigues.github.io/commit/147cdfc3c2468a03ea14020954df15d237dc9702

Let me know if this is something you are interested in.

**Comment by sergiokopplin** [comment]
I'll leave this here if someone wants the same feature for their website.

Thanks for your contribution
