### ISSUE TITLE
Blog Posts are not visible when deploying to github

### ISSUE THREAD

**Issue by Aviksaikat** [sergiokopplin/indigo#504]
![image](https://user-images.githubusercontent.com/31238298/194930388-0ea97303-176b-4115-9c3d-df316f0ea257.png)
here is the link https://aviksaikat.github.io/blog. it's working when I'm running this locally

**Comment by mehmandarov** [comment]
Hi, @Aviksaikat! Try changing category from 'project' to 'blog' in the front matter for your posts. I believe this should help.

**Comment by jonvis23** [comment]
did you solve?

**Comment by eraygokgor** [comment]
I have the same issue. I can see my blog post on my local, but when deployed I cannot see it in the blogs tab.

Today, I had a search on this topic, and when I run the following code, committed and pushed the project to the GitHub, my blog posts are started to be appear in my GitHub page. Hopefully, it will solve your problem, as well.

`bundle exec jekyll build`

**Comment by 9xN** [comment]
im having the same issue

**Comment by 9xN** [comment]
> I have the same issue. I can see my blog post on my local, but when deployed I cannot see it in the blogs tab.
> 
> Today, I had a search on this topic, and when I run the following code, committed and pushed the project to the GitHub, my blog posts are started to be appear in my GitHub page. Hopefully, it will solve your problem, as well.
> 
> `bundle exec jekyll build`

did you change the .gitignore file? and or anything else? otherwise running this would change nothing

**Comment by 9xN** [comment]
nvm got it

**Comment by sergiokopplin** [comment]
I've added a fix on pagination. We had to remove it since it has some issues with github pages.
