### ISSUE TITLE
Error when bundle install

### ISSUE THREAD

**Issue by kazumindev** [sergiokopplin/indigo#521]
when bundle install, it just like this
~/indigo $ bundle install
Fetching gem metadata from https://rubygems.org/...........Resolving dependencies...                                  Installing nokogiri 1.15.3 with native extensions          Gem::Ext::BuildError: ERROR: Failed to build gem native    extension.
                                                           current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri                                 /data/data/com.termux/files/usr/bin/ruby extconf.rb        checking for whether -std=c99 is accepted as CFLAGS... yes checking for whether -Wno-declaration-after-statement is
accepted as CFLAGS... yes                                  checking for whether -O2 is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes       checking for whether -Winline is accepted as CFLAGS... yes checking for whether -Wmissing-noreturn is accepted as     CFLAGS... yes                                              checking for whether -Wconversion -Wno-sign-conversion is
accepted as CFLAGS... yes                                  Building nokogiri using packaged libraries.
Static linking is enabled.                                 Cross build is disabled.                                   Using mini_portile version 2.8.4                           checking for iconv... yes                                  ---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of               libxml2-2.11.4.
Configuration options:                                     --host\=aarch64-unknown-linux-android --enable-static      --disable-shared                                           --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ports/aarch64-linux-android/libxml2/2.11.4/lib                                                --with-iconv\=yes --disable-dependency-tracking
--without-python --without-readline --with-c14n            --with-debug --with-threads --disable-shared               --enable-static CPPFLAGS\= CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC                                                  The following patches are being applied:
  - 0001-Remove-script-macro-support.patch                   - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch                 - 0009-allow-wildcard-namespaces.patch                   -                                                          0010-update-config.guess-and-config.sub-for-libxml2.patch  -
0011-rip-out-libxml2-s-libc_single_threaded-support.patch  
The Nokogiri maintainers intend to provide timely security updates, but if                                            this is a concern for you and want to use your OS/distro   system library                                             instead, then abort this installation process and install
nokogiri as                                                instructed at:
                                                           https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries                                                                               Note, however, that nokogiri cannot guarantee compatibility
with every                                                 version of libxml2 that may be provided by OS/package
vendors.                                                                                                              Extracting libxml2-2.11.4.tar.xz into                      tmp/aarch64-unknown-linux-android/ports/libxml2/2.11.4...  ERROR. Please review logs to see what happened:
----- contents of                                          '/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri/tmp/aarch64-unknown-linux-android/ports/libxml2/2.11.4/extract.log'                       -----                                                      tar: libxml2-2.11.4/test/relaxng/ambig_name-class.xml:     Cannot hard link to
‘libxml2-2.11.4/test/relaxng/ambig_name-class2.rng’:       Permission denied
tar: libxml2-2.11.4/test/relaxng/ambig_name-class.rng:     Cannot hard link to                                        ‘libxml2-2.11.4/test/relaxng/tutorA.rng’: Permission deniedtar: Exiting with failure status due to previous errors    ----- end of file -----
*** extconf.rb failed ***                                  Could not create Makefile due to some reason, probably lack
of necessary                                               libraries and/or headers.  Check the mkmf.log file for moredetails.  You may                                          need configuration options.                                
Provided configuration options:                                    --with-opt-dir
        --without-opt-dir                                          --with-opt-include                                         --without-opt-include=${opt-dir}/include                   --with-opt-lib                                             --without-opt-lib=${opt-dir}/lib
        --with-make-prog                                           --without-make-prog
        --srcdir=.                                                 --curdir                                           --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)                                                                  --help
        --clean                                                    --prevent-strip
        --enable-system-libraries                                  --disable-system-libraries                                 --use-system-libraries                                     --enable-system-libraries                                  --disable-system-libraries
        --use-system-libraries                                     --enable-static
        --enable-cross-build                                       --disable-cross-build                                      --enable-cross-build                                       --disable-cross-build                                      --with-zlib-dir
        --without-zlib-dir                                         --with-zlib-include
        --without-zlib-include=${zlib-dir}/include                 --with-zlib-lib                                            --without-zlib-lib=${zlib-dir}/lib                         --with-xml2-source-dir                             /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:504:in `block in execute': Failed to complete extract task
(RuntimeError)                                             from                                                       /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `chdir'
from                                                       /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `execute'                                                  from                                                       /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:456:in
`extract_file'                                             from
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:118:in `block in extract'                                         from                                                       /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:116:in `each'
from                                                       /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:116:in `extract'                                                  from
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:211:in
`cook'                                                     from extconf.rb:540:in `block (2 levels) in                process_recipe'                                                    from extconf.rb:319:in `chdir'                             from extconf.rb:319:in `chdir_for_build'
        from extconf.rb:540:in `block in process_recipe'           from <internal:kernel>:90:in `tap'
        from extconf.rb:438:in `process_recipe'                    from extconf.rb:872:in `<main>'                                                                               To see why this extension failed to compile, please check  the mkmf.log which can be found here:
                                                           /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.15.3/mkmf.log                                                              extconf failed, exit code 1                                                                                           Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3
for inspection.                                            Results logged to                                          /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.15.3/gem_make.out
                                                           /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in                                         `run'                                                      /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:27:in                                 `build'
/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in
`build_extension'                                          /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in                                         `block in build_extensions'                                /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in                                         `each'
/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in                                         `build_extensions'                                         /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/installer.rb:843:in
`build_extensions'                                         /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:72:in   `build_extensions'                                         /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:28:in   `install'
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in
`install'                                                  /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in  `install'                                                  /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in  `install_from_spec'
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in                                                       `do_install'                                               /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in
`block in worker_pool'                                     /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in                   `apply_func'                                               /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in                   `block in process_queue'
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in                   `loop'                                                     /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in
`process_queue'                                            /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in                   `block (2 levels) in create_threads'
                                                           An error occurred while installing nokogiri
(1.15.3), and Bundler cannot continue.                     
In Gemfile:                                                  github-pages was resolved to 228, which depends on
    jekyll-mentions was resolved to 1.6.0, which depends on
html-pipeline was resolved to 2.14.3, which depends        on                                                                 nokogiri                                          

while install nokogiri using 'gem install nokogiri" come like this:
~/indigo $ gem install nokogiri                            Building native extensions. This could take a while...     ERROR:  Error installing nokogiri:                                 ERROR: Failed to build gem native extension.
    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri          /data/data/com.termux/files/usr/bin/ruby extconf.rb        checking for whether -std=c99 is accepted as CFLAGS... yes checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes      checking for whether -O2 is accepted as CFLAGS... yes      checking for whether -g is accepted as CFLAGS... yes       checking for whether -Winline is accepted as CFLAGS... yes checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes                                                  checking for whether -Wconversion -Wno-sign-conversion is accepted as CFLAGS... yesBuilding nokogiri using packaged libraries.                Static linking is enabled.                                 Cross build is disabled.                                   Using mini_portile version 2.8.4                           checking for iconv... yes                                  ---------- IMPORTANT NOTICE ----------                     Building Nokogiri with a packaged version of libxml2-2.11.4.                                                          Configuration options: --host\=aarch64-unknown-linux-android --enable-static --disable-shared --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ports/aarch64-linux-android/libxml2/2.11.4/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CPPFLAGS\= CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC                                       The following patches are being applied:                     - 0001-Remove-script-macro-support.patch                   - 0002-Update-entities-to-remove-handling-of-ssi.patch     - 0003-libxml2.la-is-in-top_builddir.patch                 - 0009-allow-wildcard-namespaces.patch                        - 0010-update-config.guess-and-config.sub-for-libxml2.patch                                                           - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch                                     The Nokogiri maintainers intend to provide timely security updates, but if                                  this is a concern for you and want to use your OS/distro system library                                               instead, then abort this installation process and install nokogiri as                                                 instructed at:                                  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries        Note, however, that nokogiri cannot guarantee compatibility with every                                                version of libxml2 that may be provided by OS/package vendors.                                    Extracting libxml2-2.11.4.tar.xz into tmp/aarch64-unknown-linux-android/ports/libxml2/2.11.4... ERROR. Please review logs to see what happened:                                  ----- contents of '/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri/tmp/aarch64-unknown-linux-android/ports/libxml2/2.11.4/extract.log' -----                       tar: libxml2-2.11.4/test/relaxng/ambig_name-class.xml: Cannot hard link to ‘libxml2-2.11.4/test/relaxng/ambig_name-class2.rng’: Permission denied                                tar: libxml2-2.11.4/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.11.4/test/relaxng/tutorA.rng’: Permission denied                                           tar: Exiting with failure status due to previous errors                                       ----- end of file -----                                    *** extconf.rb failed ***                                  Could not create Makefile due to some reason, probably lack of necessary                                              libraries and/or headers.  Check the mkmf.log file for more details.  You may                                         need configuration options.
Provided configuration options:                                    --with-opt-dir                                             --without-opt-dir                                          --with-opt-include                                         --without-opt-include=${opt-dir}/include                   --with-opt-lib                                         --without-opt-lib=${opt-dir}/lib                           --with-make-prog                                           --without-make-prog                                        --srcdir=.                                                 --curdir                                                   --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)                       --help                                                     --clean                                                    --prevent-strip                                            --enable-system-libraries                                  --disable-system-libraries                                 --use-system-libraries                                     --enable-system-libraries                                                     --disable-system-libraries                                 --use-system-libraries                                     --enable-static                                            --enable-cross-build                                       --disable-cross-build                                      --enable-cross-build                                       --disable-cross-build
--with-zlib-dir                                            --without-zlib-dir                                         --with-zlib-include                                        --without-zlib-include=${zlib-dir}/include                 --with-zlib-lib                                            --without-zlib-lib=${zlib-dir}/lib                         --with-xml2-source-dir                                                /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:504:in `block in execute': Failed to complete extract task (RuntimeError)                                                            from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `chdir'            from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `execute'                                             from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:456:in `extract_file'                                        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:118:in `block in extract'                                    from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:116:in `each'                                                from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:116:in `extract'                                             from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:211:in `cook'                                                from extconf.rb:540:in `block (2 levels) in process_recipe'                   from extconf.rb:319:in `chdir'                                from extconf.rb:319:in `chdir_for_build'                   from extconf.rb:540:in `block in process_recipe'           from <internal:kernel>:90:in `tap'                         from extconf.rb:438:in `process_recipe'                    from extconf.rb:872:in `<main>'                                                 To see why this extension failed to compile, please check the mkmf.log which can be found here:               /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.15.3/mkmf.log                                             extconf failed, exit code 1

**Comment by sergiokopplin** [comment]
There are a lot of issues using ruby and Jekyll. Can you take a look at the site docs? https://jekyllrb.com/docs/usage/
