### ISSUE TITLE
github-pages can't satisfy your Gemfile's dependencies.

### ISSUE THREAD

**Issue by mehmandarov** [sergiokopplin/indigo#523]
Deploying directly using GitHub Actions results in the following warning:

`github-pages can't satisfy your Gemfile's dependencies.`

Could it be because some of the plugins in the Gemfile are not on the list here: https://pages.github.com/versions/ ?

**Comment by sergiokopplin** [comment]
I'll take a look

**Comment by sergiokopplin** [comment]
I think it was related to pagination since was not a GitHub-pages supported package. So I had to completely remove pagination for now
