### ISSUE TITLE
Blog posts are not displayed if the month of the date is 10, 11 or 12 (October to December)

### ISSUE THREAD

**Issue by ghost** [sergiokopplin/indigo#524]
If the blog post date is prefixed with a '1' (e.g. October - 10, November - 11 and December - 12) the blog posts are not displayed. This is only for the date format in the header of the markdown file. If prefixed with a '0' (January to September) everything works fine.

**Comment by ghost** [comment]
Turns out if I simply specify the month with text (e.g. "16-October-2023") it does indeed work. Interestingly, the current date will not be displayed. But that is not really an issue.

**Comment by nielswritescode** [comment]
Setting future: true in _comfig.yml is also an option (causing blog posts that are in the future to display).
