### ISSUE TITLE
CONTRIBUTING.md deserves an update!

### ISSUE THREAD

**Issue by HimanshuMahto** [sergiokopplin/indigo#529]
Unlike other amazing repos, this repo's CONTRIBUTING.md looks plain and simple.

i think emojified, fun and precise version would be better!

Describe alternatives you've considered
An update would be amazing!

Additional context
If you are reading this, you are amazing! ⭐

Starred ⭐✔️

Thanks and regards,
Himanshu

**Comment by HimanshuMahto** [comment]
@antenore @brenodamata @DzikowskiW @renatogalvones  Created a PR please do review it #530.

**Comment by sergiokopplin** [comment]
Done! Thank you
