### ISSUE TITLE
updating styling for tweet/share button in post author bio

### ISSUE THREAD

**Issue by aannasw** [sergiokopplin/indigo#53]
Hi Sérgio, I'm using your theme on my site - thanks so much, it's awesome! I just had a question regarding updating the styling for the Twitter and Facebook share buttons in the author bio section on blog posts. 

I found and updated the colors in both assets/styles/main.css and src/styles/components/_share.styl but don't see any changes on my site. Am I missing any other code I need to update?

**Comment by aannasw** [comment]
Ah, missed the _includes/main.css :) All good!

**Comment by sergiokopplin** [comment]
i'm looking you app and i think you need to update the files!
do you know how to do this?
