### ISSUE TITLE
Feature request: Support for light theme

### ISSUE THREAD

**Issue by anniepauline** [sergiokopplin/indigo#534]
Currently, the option to change the theme of the site has to be given through a YML config file. Create a feature that contains a button that toggles the theme from light to dark and vice versa. That way we can add more flexibility to the user

**Comment by sergiokopplin** [comment]
https://github.com/sergiokopplin/indigo/blob/gh-pages/_config.yml#L13

**Comment by anniepauline** [comment]
Added a detailed feature request!

**Comment by sergiokopplin** [comment]
Oh, sorry. My mistake
Can you help us with that?

**Comment by anniepauline** [comment]
sure, would be glad to!!
