### ISSUE TITLE
Issue with blog index spacing.

### ISSUE THREAD

**Issue by KPdir** [sergiokopplin/indigo#70]
Hi Sérgio, very nice theme, really like the aesthetics and functionality. I'm just getting set up but am having a issue with blog spacing on the index page, i.e. there is a huge gap between each of the list items and I don't understand where that might be coming from. Here is a link to the [page](http://kpdir.github.io/blog/).

I haven't made many modifications to the structure so far. They are: 1) added a minimal header without the photo on the "Blog" and "Projects" pages as described [here](http://artiannaswamy.com/build-a-github-blog-part-2#different-headers). 2) Included the line `{% include Math_Jax.html %}`  in `post.html` and added a file Math_Jax.html which to `_includes` which contains the line `<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>`. 

Any help or pointers very much appreciated. 

Thanks!
Kedar

**Comment by brenodamata** [comment]
I just started having that same issue. I think it happens after the 3rd blog post.

**Comment by sandeshsoni** [comment]
Even i am facing the same issue here http://sandeshsoni.com/blog/

It looks perfect locally. When compared both code,
- strict html is not set
- html lang="pt-BR" is also not set.

**Comment by sergiokopplin** [comment]
Thank you guys for the feedback. I'm looking this right now!

:metal:

**Comment by sergiokopplin** [comment]
Gap between posts and HTML Lang [solved](https://github.com/sergiokopplin/indigo/commit/346b511de3c228158de92f19d104af9feb3236a3).

@sandeshsoni: what's the problem with "strict html"? I don't get it.

Thank you guys for the comments!

---

[Update](https://help.github.com/articles/syncing-a-fork/) your forks now.

---

Give me a feedback later, please!

**Comment by sandeshsoni** [comment]
@sergiokopplin 
Doctype missing on live site. It was 100% height on both the places

<img width="902" alt="screen shot 2016-03-11 at 6 04 53 pm" src="https://cloud.githubusercontent.com/assets/3761745/13702436/a53cbb0c-e7b4-11e5-90e9-b4eb4687fadc.png">
<img width="948" alt="screen shot 2016-03-11 at 6 05 21 pm" src="https://cloud.githubusercontent.com/assets/3761745/13702437/a75642be-e7b4-11e5-8d0f-0c612bc0c55c.png">

**Comment by sergiokopplin** [comment]
@sandeshsoni.

---

Localhost:

![screen shot 2016-03-11 at 9 47 22 am](https://cloud.githubusercontent.com/assets/2743180/13702571/5a46cd4a-e76e-11e5-92d6-3bdf9305cfb3.png)

---

Production:

![screen shot 2016-03-11 at 9 48 28 am](https://cloud.githubusercontent.com/assets/2743180/13702597/7e43abf0-e76e-11e5-9e80-ac17b820ad1b.png)

---

I don't know why this is happening. Do you have any idea?
It's working on localhost, but when it's compressed, some html disappear.

**Comment by sergiokopplin** [comment]
@KPdir, do you have any other problems? Something with the math?

**Comment by sandeshsoni** [comment]
@sergiokopplin 
No, I dont have any idea.
I am investigating. If i find something, i will get back to you.

**Comment by sergiokopplin** [comment]
Thank you for your help @sandeshsoni. If you need something, tell me.

**Comment by KPdir** [comment]
@sergiokopplin,  thanks for asking :). Math seems to render alright with the changes I mentioned in my opening post. I just tried entering a couple equations in one of the posts and it seemed to work, so no problems so far.  

About the blog posts spacing. Great to hear its fixed. I am yet to update my fork though. I did not mention earlier that the same issue applies to Projects page as well. Does the fix work for both?  

Many Thanks

**Comment by sergiokopplin** [comment]
@KPdir Both. Test later and tell me, please.

**Comment by KPdir** [comment]
It did not work, I must have screwed up syncing the fork perhaps. Do I need to have both gh-pages and master brach in my fork? Because after I had initially forked indigo, I made a master branch and deleted the gh-pages branch both locally and on my github. 

I can delete my website and re-fork your latest scheme and apply the changes I have made from then on. Does not seem to be a big hassle at the moment but I do need to figure out how to properly sync to Indigo main repository under you.

**Comment by sergiokopplin** [comment]
Just update from gh-pages to your master. You can do that!

**Comment by KPdir** [comment]
Not sure how I can do that but will try to find out. But main thing, I can confirm it is fixed now. :+1: 

Thanks a lot!

**Comment by sergiokopplin** [comment]
@KPdir: try that

git fetch origin
git merge gh-pages
git push origin master

**Comment by brenodamata** [comment]
The fix worked for me @sergiokopplin!

Thanks! 👍🏽
