### ISSUE TITLE
Duplication of title tags

### ISSUE THREAD

**Issue by sandeshsoni** [sergiokopplin/indigo#71]
@sergiokopplin 

I can see there are multiple title tags.

I suspect this issue is related to DOCTYPE not being set.

<img width="561" alt="screen shot 2016-03-11 at 8 37 27 pm" src="https://cloud.githubusercontent.com/assets/3761745/13706046/7668f8bc-e7c9-11e5-98dd-b98017eff421.png">

**Comment by sergiokopplin** [comment]
@sandeshsoni it's in before the render!
Jekyll is pulling them off, i don't know why.

Localhost has a different result, so i'm doubt of where is the problem

**Comment by sergiokopplin** [comment]
@sandeshsoni, solved!
