### ISSUE TITLE
How to generate jemoji image links on project page?

### ISSUE THREAD

**Issue by KPdir** [sergiokopplin/indigo#72]
Hi @sergiokopplin  and Indigo users

I am not clear how to generate emoji image links that appear in the project title page in front of "jemoji:" (example: https://assets.github.com/images/icons/emoji/unicode/1f4da.png). I do not use Jekyll locally to generate my site. I currently just push changes directly on to github pages since i had some trouble installing Jekyll.  Could someone point out how the links to these images are generated? 

Thanks, 
Kedar

**Comment by sergiokopplin** [comment]
Hi @KPdir, sorry about this. I forgot to explain how to create projects with emojis.
I'll do this later, but it's on my schedule now.

**Comment by KPdir** [comment]
Sounds good, but is this a feature I can only use if I am generating my site locally?

**Comment by sergiokopplin** [comment]
@KPdir, sorry for the delay.
I'm gonna look this issue this week.

**Comment by sergiokopplin** [comment]
Ok, so what i do?
I put a jemoji inside a post, like `:metal:`, which is :metal: in the rendered version. 
So i go to devtools and look at the id for the image:

![screen shot 2016-03-30 at 1 57 59 pm](https://cloud.githubusercontent.com/assets/2743180/14150462/7cd0d516-f67f-11e5-8713-6d8b587eda31.png)

So, in this case is 2744. So i can put that code inside the config for the post:

`jemoji: <img class="emoji" title=":snowflake:" alt=":snowflake:" src="https://assets.github.com/images/icons/emoji/unicode/2744.png" height="20" width="20" align="absmiddle">`

---

It's not the best way, but was the only way for me.
Hope that help's you!

**Comment by sergiokopplin** [comment]
closed

**Comment by KPdir** [comment]
Thanks @sergiokopplin  :+1: , I haven't got a chance to try it yet but will do

**Comment by vhbsouza** [comment]
@sergiokopplin @KPdir  I've managed to do this in a better way. Now I can use emoji shortcodes directly in the title like this.

```yaml
title: ":ramen: Hello World :warning:"
```
and shows title: ":ramen: Hello World :warning:"

If it interests you I can do a PR with this change.

**Comment by sergiokopplin** [comment]
@vhbsouza please!!!! Back in the time i put the emoji, this was not possible (or i didn't find a way). Thanks man!!!!

**Comment by sergiokopplin** [comment]
@vhbsouza how you did that man? hahaha i'm curious

**Comment by lichen999** [comment]
Hi, when I tried to use the short code of emoji mentioned above in the markdown file, the picture is quite big when on my github page, any idea how to resize it? Thanks
