### ISSUE TITLE
Use Piwik instead GA

### ISSUE THREAD

**Issue by Fohlen** [sergiokopplin/indigo#8]
Would it be possible to add Piwik instead Google Analytics because I am a bit privacy concerned? :+1:

**Comment by sergiokopplin** [comment]
yes, we can put that inside.
do you have any link or documentation about?
i really don't know about this tool.

thank you for the open issue!

**Comment by Fohlen** [comment]
Examples can be found at http://piwik.org/integrate/
I'll append a sample right here

```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.darkkeepers.dk","*.www.darkkeepers.dk"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//piwik.berger.work/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//piwik.berger.work/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
```

**Comment by sergiokopplin** [comment]
what variables you have to change? setDomains? 
I can't find this example in the _integrations_ page.

I know that is just JS, but i want to take a look first. o//

**Comment by Fohlen** [comment]
You need to change the origin which is

``` js
var u="//piwik.berger.work"
```

as well as allowed domains

``` js
  _paq.push(["setDomains", ["*.darkkeepers.dk","*.www.darkkeepers.dk"]]);
```

This is probably best done when you add a condition (like, piwik-enabled) and let the user insert the tracking code form within their Piwik into the configuration, alike

``` yml
piwik_enabled = true
piwik_code = '<codegoeshere>'
```

**Comment by sergiokopplin** [comment]
i'll test this later, but it's a nice tool. i like it!

**Comment by sergiokopplin** [comment]
@Fohlen, how can i see the analytics page for piwik?
I can't find!

**Comment by sergiokopplin** [comment]
@Fohlen i couldn't find any documentation for this, like examples and admin area.
If you can help, we can open this again. But for now, i'm closing.

**Comment by Fohlen** [comment]
I've found the following article
- http://minuteware.net/2013-12-22-integrate-piwik-into-jekyll.html

Covering how to embed Piwik into Jekyll!
