### ISSUE TITLE
[Need help] Build okay locally, bug on site

### ISSUE THREAD

**Issue by npvinhphat** [sergiokopplin/indigo#87]
When I build with gulp locally, the site is okay, but when I push it to github, there are some problems with the metadata.

[My site](http://npvinhphat.github.io)
[My repository](https://github.com/npvinhphat/npvinhphat.github.io)

Thank for any help :)

**Comment by sergiokopplin** [comment]
Here is the problem (i guess): [https://github.com/npvinhphat/npvinhphat.github.io/pull/1](https://github.com/npvinhphat/npvinhphat.github.io/pull/1)
