### ISSUE TITLE
Social link mouse-over URL display truncates linkedin

### ISSUE THREAD

**Issue by tombusby** [sergiokopplin/indigo#97]
I'm not sure how to fix this one, or I'd put a patch in myself.

http://tom.busby.ninja/

Check out my little boiler-plate blog. If you mouse-over linkedin, the href is actually correct, but it stops displaying the linkedin URL after the first `-`.

As such, `http://linkedin.com/in/thomas-busby-74482b54` becomes `http://linkedin.com/in/thomas-`

**Comment by tombusby** [comment]
Figured it out, just a line-breaking (combined with `overflow: hidden`) issue.

**Comment by sergiokopplin** [comment]
Thank you for reporting the issue.
